// content/guia/cities/cdmx.ts
//
// City layer for Mexico City. Reusable across partners. Copy ported verbatim
// from the exported design (prototypes/Guest Stay Experience Design). Do not
// rewrite — this is the approved bilingual copy.

import type { City } from '../types'

const MAPS = (query: string) =>
  `https://www.google.com/maps/search/?api=1&query=${query}`

export const cdmx: City = {
  id: 'cdmx',
  heroImage: '/images/guia/cdmx-banner.jpg',
  neighborhoodOrder: ['Roma Norte', 'Condesa', 'Polanco', 'Centro'],

  neighborhoods: {
    'Roma Norte': {
      name: 'Roma Norte',
      mapUrl: MAPS('Roma+Norte+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'coffee',     name: 'Café Avellaneda',       distance: '4 min caminando',  note: 'Café de lote pequeño, del que regresas dos veces.' },
          { icon: 'croissant',  name: 'Panadería Rosetta',     distance: '6 min caminando',  note: 'Los panes de guayaba se acaban antes de las 10am, llega temprano.' },
          { icon: 'utensilsSm', name: 'Contramar',             distance: '10 min caminando', note: 'Las tostadas de atún ya valen el viaje. No se necesita reservación en la comida.' },
          { icon: 'basket',     name: 'Mercado Roma',          distance: '8 min caminando',  note: 'Un mercado gourmet para una comida rápida o vino por la tarde.' },
          { icon: 'trees',      name: 'Parque México',         distance: '3 min caminando',  note: 'Bancas art déco, paseadores de perros, y el mejor lugar para observar gente.' },
          { icon: 'cross',      name: 'Farmacias del Ahorro',  distance: '5 min caminando',  note: 'Abierto hasta tarde, para lo que se te olvidó empacar.' },
        ],
        en: [
          { icon: 'coffee',     name: 'Café Avellaneda',       distance: '4 min walk',  note: 'Small-batch coffee, the kind of place you return to twice.' },
          { icon: 'croissant',  name: 'Panadería Rosetta',     distance: '6 min walk',  note: 'Guava rolls sell out by 10am, go early.' },
          { icon: 'utensilsSm', name: 'Contramar',             distance: '10 min walk', note: 'The tuna tostadas alone are worth the trip. No reservations needed at lunch.' },
          { icon: 'basket',     name: 'Mercado Roma',          distance: '8 min walk',  note: 'A gourmet market for a quick, easy lunch or evening wine.' },
          { icon: 'trees',      name: 'Parque México',         distance: '3 min walk',  note: 'Art deco benches, dog walkers, and the best people-watching in the city.' },
          { icon: 'cross',      name: 'Farmacias del Ahorro',  distance: '5 min walk',  note: 'Open late, for anything you forgot to pack.' },
        ],
      },
      perfectDay: {
        es: [
          { time: '8:00',  title: 'Café en Avellaneda',                 body: 'Pídelo para llevar; la banca bajo el jacarandá de la esquina es la mejor mesa.' },
          { time: '8:30',  title: 'Una vuelta por Parque México',       body: 'El anfiteatro está vacío antes de las nueve, el mejor momento del día.' },
          { time: '13:00', title: 'Comida en Contramar',                body: 'El atún tostada y el pescado a la talla, en ese orden. Llega antes de la 1:30pm.' },
          { time: '16:00', title: 'Museo Tamayo',                       body: 'Colección compacta, se recorre entera en una hora sin cansarse.' },
          { time: '19:00', title: 'Coctel en Licorería Limantour',      body: 'El Smoking No. 5 es el que piden los que ya conocen la carta.' },
          { time: '21:00', title: 'Cena en Rosetta',                    body: 'Reserva con dos semanas de anticipación; el pan de elote se acaba temprano.' },
        ],
        en: [
          { time: '8:00',  title: 'Coffee at Café Avellaneda',          body: 'Get it to go; the bench under the corner jacaranda is the best table.' },
          { time: '8:30',  title: 'A loop through Parque México',       body: 'The amphitheater sits empty before nine, the best hour the park has.' },
          { time: '13:00', title: 'Lunch at Contramar',                 body: 'Tuna tostada first, pescado a la talla second. Arrive before 1:30pm.' },
          { time: '16:00', title: 'Museo Tamayo',                       body: 'A compact collection, walkable start to finish in an hour without tiring.' },
          { time: '19:00', title: 'Cocktail at Licorería Limantour',    body: 'Order the Smoking No. 5, it\'s what the regulars ask for.' },
          { time: '21:00', title: 'Dinner at Rosetta',                  body: 'Book two weeks out; the corn bread sells out early.' },
        ],
      },
    },

    'Condesa': {
      name: 'Condesa',
      mapUrl: MAPS('Condesa+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'croissant',  name: 'Lardo',                 distance: '5 min caminando', note: 'Panadería y bistró en una sola parada, perfecto para el desayuno.' },
          { icon: 'utensilsSm', name: 'El Parnita',            distance: '7 min caminando', note: 'Cocina mexicana de mar, casual y siempre con fila corta.' },
          { icon: 'basket',     name: 'Mercado Michoacán',     distance: '6 min caminando', note: 'El mercado de barrio, fruta, flores, y puestos de comida honestos.' },
          { icon: 'trees',      name: 'Parque España',         distance: '3 min caminando', note: 'Más chico y tranquilo que Parque México, ideal para las mañanas.' },
          { icon: 'trees',      name: 'Parque México',         distance: '6 min caminando', note: 'El corazón verde de la colonia, anfiteatro, viveros, y bancas art déco.' },
          { icon: 'cross',      name: 'Farmacias del Ahorro',  distance: '4 min caminando', note: 'Abierto hasta tarde, para lo que se te olvidó empacar.' },
        ],
        en: [
          { icon: 'croissant',  name: 'Lardo',                 distance: '5 min walk', note: 'Bakery and bistro in one stop, perfect for breakfast.' },
          { icon: 'utensilsSm', name: 'El Parnita',            distance: '7 min walk', note: 'Casual Mexican seafood, always with a short line.' },
          { icon: 'basket',     name: 'Mercado Michoacán',     distance: '6 min walk', note: 'The neighborhood market, fruit, flowers, and honest food stalls.' },
          { icon: 'trees',      name: 'Parque España',         distance: '3 min walk', note: 'Smaller and quieter than Parque México, ideal for mornings.' },
          { icon: 'trees',      name: 'Parque México',         distance: '6 min walk', note: 'The green heart of the neighborhood, amphitheater, nursery, art deco benches.' },
          { icon: 'cross',      name: 'Farmacias del Ahorro',  distance: '4 min walk', note: 'Open late, for anything you forgot to pack.' },
        ],
      },
      perfectDay: {
        es: [
          { time: '8:00',  title: 'Café y pan en Lardo',                     body: 'Llega temprano, las mesas de la terraza se llenan rápido.' },
          { time: '8:30',  title: 'Parque España y Parque México',          body: 'Una caminata tranquila entre los dos parques de la colonia.' },
          { time: '13:00', title: 'Comida en El Parnita',                   body: 'Los tacos de pescado son el platillo por el que vale la pena ir.' },
          { time: '16:00', title: 'Museo Nacional de Antropología',         body: 'A un paseo corto en Chapultepec, la colección más importante del país.' },
          { time: '19:00', title: 'Coctel en Baltra Bar',                   body: 'Mezcal y jazz, en un espacio pequeño e íntimo.' },
          { time: '21:00', title: 'Cena en El Tizoncito',                   body: 'El lugar que se atribuye la invención del taco al pastor.' },
        ],
        en: [
          { time: '8:00',  title: 'Coffee and bread at Lardo',              body: 'Get there early, the terrace tables fill up fast.' },
          { time: '8:30',  title: 'Parque España and Parque México',        body: 'An easy walk between the neighborhood\'s two parks.' },
          { time: '13:00', title: 'Lunch at El Parnita',                    body: 'The fish tacos are the dish worth the trip.' },
          { time: '16:00', title: 'Museo Nacional de Antropología',         body: 'A short ride into Chapultepec, the country\'s most important collection.' },
          { time: '19:00', title: 'Cocktail at Baltra Bar',                 body: 'Mezcal and jazz, in a small, intimate space.' },
          { time: '21:00', title: 'Dinner at El Tizoncito',                 body: 'The spot credited with inventing the taco al pastor.' },
        ],
      },
    },

    'Polanco': {
      name: 'Polanco',
      mapUrl: MAPS('Polanco+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'coffee',    name: 'Blend Station',          distance: '5 min caminando',  note: 'Café de especialidad, ideal para trabajar una hora.' },
          { icon: 'trees',     name: 'Parque Lincoln',         distance: '4 min caminando',  note: 'Pavorreales, kiosco y las mejores bancas para leer.' },
          { icon: 'landmark',  name: 'Museo Soumaya',          distance: '10 min caminando', note: 'Entrada gratuita, arquitectura inconfundible.' },
          { icon: 'landmark',  name: 'Museo Jumex',            distance: '10 min caminando', note: 'Arte contemporáneo, justo al lado del Soumaya.' },
          { icon: 'basket',    name: 'Antara Fashion Hall',    distance: '12 min caminando', note: 'Para una tarde de tiendas o una copa con vista.' },
          { icon: 'cross',     name: 'Farmacias del Ahorro',   distance: '5 min caminando',  note: 'Abierto hasta tarde, para lo que se te olvidó empacar.' },
        ],
        en: [
          { icon: 'coffee',    name: 'Blend Station',          distance: '5 min walk',  note: 'Specialty coffee, good for an hour of work.' },
          { icon: 'trees',     name: 'Parque Lincoln',         distance: '4 min walk',  note: 'Peacocks, a bandstand, and the best benches for reading.' },
          { icon: 'landmark',  name: 'Museo Soumaya',          distance: '10 min walk', note: 'Free entry, unmistakable architecture.' },
          { icon: 'landmark',  name: 'Museo Jumex',            distance: '10 min walk', note: 'Contemporary art, right next to Soumaya.' },
          { icon: 'basket',    name: 'Antara Fashion Hall',    distance: '12 min walk', note: 'For an afternoon of shopping or a drink with a view.' },
          { icon: 'cross',     name: 'Farmacias del Ahorro',   distance: '5 min walk',  note: 'Open late, for anything you forgot to pack.' },
        ],
      },
      perfectDay: {
        es: [
          { time: '8:00',  title: 'Café en Blend Station',        body: 'Un espacio tranquilo antes de que empiece el ajetreo del día.' },
          { time: '8:30',  title: 'Vuelta por Parque Lincoln',    body: 'El respiro verde de Polanco, con pavorreales incluidos.' },
          { time: '13:00', title: 'Comida en Dulce Patria',       body: 'Cocina mexicana contemporánea de Martha Ortiz, reserva con antelación.' },
          { time: '16:00', title: 'Museo Soumaya',                body: 'Entrada gratuita, una hora fácil, arquitectura que vale la foto.' },
          { time: '19:00', title: 'Copa cerca de Antara',         body: 'Termina la tarde con una copa y algo de shopping ligero.' },
          { time: '21:00', title: 'Cena en Pujol',                body: 'Reserva con semanas de anticipación, vale cada una de ellas.' },
        ],
        en: [
          { time: '8:00',  title: 'Coffee at Blend Station',      body: 'A calm space before the day picks up pace.' },
          { time: '8:30',  title: 'A loop through Parque Lincoln', body: 'Polanco\'s green breather, peacocks included.' },
          { time: '13:00', title: 'Lunch at Dulce Patria',        body: 'Martha Ortiz\'s contemporary Mexican cooking, book ahead.' },
          { time: '16:00', title: 'Museo Soumaya',                body: 'Free entry, an easy hour, architecture worth the photo.' },
          { time: '19:00', title: 'A drink near Antara',          body: 'Close out the afternoon with a drink and some light shopping.' },
          { time: '21:00', title: 'Dinner at Pujol',              body: 'Book weeks ahead, it\'s worth every one of them.' },
        ],
      },
    },

    'Centro': {
      name: 'Centro',
      mapUrl: MAPS('Centro+Historico+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'coffee',     name: 'Café El Popular',         distance: 'en el Centro', note: 'Abierto casi 24 horas, café de olla y pan dulce.' },
          { icon: 'utensilsSm', name: 'Café de Tacuba',          distance: 'en el Centro', note: 'Desde 1912, cocina mexicana en un salón de azulejos.' },
          { icon: 'basket',     name: 'Mercado de San Juan',     distance: 'en el Centro', note: 'El mercado gourmet de la ciudad, para probar de todo.' },
          { icon: 'landmark',   name: 'Templo Mayor',            distance: 'en el Centro', note: 'Ruinas mexicas a un costado de la Catedral.' },
          { icon: 'landmark',   name: 'Palacio de Bellas Artes', distance: 'en el Centro', note: 'El teatro más bello del país, murales incluidos.' },
          { icon: 'cross',      name: 'El Moro',                 distance: 'en el Centro', note: 'Churros y chocolate desde 1935, abierto toda la noche.' },
        ],
        en: [
          { icon: 'coffee',     name: 'Café El Popular',         distance: 'in the Centro', note: 'Open nearly 24 hours, café de olla and sweet bread.' },
          { icon: 'utensilsSm', name: 'Café de Tacuba',          distance: 'in the Centro', note: 'Since 1912, Mexican cooking in a tiled dining room.' },
          { icon: 'basket',     name: 'Mercado de San Juan',     distance: 'in the Centro', note: 'The city\'s gourmet market, taste a bit of everything.' },
          { icon: 'landmark',   name: 'Templo Mayor',            distance: 'in the Centro', note: 'Aztec ruins right beside the Cathedral.' },
          { icon: 'landmark',   name: 'Palacio de Bellas Artes', distance: 'in the Centro', note: 'The country\'s most beautiful theater, murals included.' },
          { icon: 'cross',      name: 'El Moro',                 distance: 'in the Centro', note: 'Churros and chocolate since 1935, open all night.' },
        ],
      },
      // Source has no perfect-day for Centro; only the home colonia's perfect
      // day is ever rendered, so this stays empty.
      perfectDay: { es: [], en: [] },
    },
  },

  destinations: [
    { name: 'Oaxaca',                 photoUrl: '/images/guides/oaxaca.jpg' },
    { name: 'Tulum',                  photoUrl: '/images/guides/tulum.jpg' },
    { name: 'San Miguel de Allende',  photoUrl: '/images/guides/san-miguel-de-allende.jpg' },
    { name: 'Valle de Bravo',         photoUrl: '/images/guides/valle-de-bravo.jpg' },
    { name: 'Mérida',                 photoUrl: '/images/guides/merida.jpg' },
  ],

  copy: {
    es: {
      navLabel: 'Tu estancia',
      heroEyebrow: 'Curado por {host} · Potenciado por Lagomplan',
      heroTitle: 'Bienvenido a la Ciudad de México.',
      heroSub: 'Todo lo que necesitas para tu estancia en {neighborhood}, preparado como lo haría un amigo, no un buscador.',
      beginExploring: 'Empezar a explorar',
      beforeEyebrow: 'Antes de llegar',
      beforeH2: 'Un inicio tranquilo para tu viaje',
      beforeLede: 'Lo básico y práctico, para que dejes de pensar en logística en cuanto aterrices.',
      arrivalItems: [
        { icon: 'plane',     title: 'Aeropuerto',      body: 'La mayoría de los vuelos llegan al AICM (Terminal 1 o 2). De ahí, un taxi autorizado o Uber tarda 30–45 min a {neighborhood}. Podemos ofrecerte también transporte privado.' },
        { icon: 'car',       title: 'Transporte',      body: 'Usa Uber o Didi, más barato y seguro que parar un taxi en la calle. El Metro es excelente si te sientes cómodo entre multitudes. O si prefieres podemos coordinar transporte para ti.' },
        { icon: 'cloudSun',  title: 'Clima',           body: 'Julio es temporada de lluvias, mañanas soleadas, lluvias breves por la tarde. Lleva capas y una chamarra ligera para la lluvia.' },
        { icon: 'banknote',  title: 'Dinero',          body: 'Las tarjetas se aceptan ampliamente. Lleva algo de efectivo en pesos para mercados, propinas y comida callejera. En restaurantes, la propina recomendada es 10–15%; redondea en taxis y puestos casuales.' },
        { icon: 'wifi',      title: 'Conectividad',    body: 'Un eSIM se activa en minutos. ', link: { text: 'Consigue el tuyo con Airalo aquí', href: 'https://airalo.tpm.li/xkRXTIKe', after: '. El wifi es confiable en la propiedad y en la mayoría de los cafés.' } },
        { icon: 'shield',    title: 'Seguridad',       body: 'Aplica el sentido común habitual en ciudad, usa apps de transporte por la noche y mantén tus objetos de valor fuera de vista.' },
        { icon: 'briefcase', title: 'Equipaje',        body: 'Zapatos cómodos para caminar, un outfit elegante para la cena, y una capa ligera para las noches frescas.' },
        { icon: 'droplet',   title: 'Agua de la llave', body: 'Te recomendamos agua embotellada o filtrada para tomar. Es segura para bañarte y lavarte los dientes.' },
        { icon: 'moon',      title: 'Llegar tarde',    body: 'Llega a la hora que sea, no hay problema. Solo te pedimos entrar con calma, es un edificio con vecinos.' },
        { icon: 'parking',   title: 'Estacionamiento', body: 'El estacionamiento en la calle es limitado en la zona. Te recomendamos llegar en Uber o Didi en vez de traer coche.' },
      ],
      neighborhoodEyebrow: 'Tu colonia',
      neighborhoodH2Prefix: 'La vida alrededor de ',
      neighborhoodLede: 'Todo está a pocos pasos. Esto es lo que te recomendaría si me preguntaras en el desayuno.',
      openInMapsLabel: 'Ver lista en Maps',
      perfectDayEyebrow: 'Un día perfecto',
      perfectDayH2: 'Si tuviera un solo día aquí',
      perfectDayLede: 'Esto es exactamente lo que haría, de principio a fin.',
      moodEyebrow: 'Explora según tu ánimo',
      moodH2: '¿Qué se te antoja hoy?',
      moodLede: 'Elige un ánimo, no una categoría.',
      moods: [
        { id: 'hungry',    icon: 'utensils', label: 'Tengo hambre',          title: 'Para cuando tienes hambre', items: [
          { name: 'Contramar',           note: 'Mariscos, sin reservación para la comida.' },
          { name: 'Panadería Rosetta',   note: 'Panes que valen madrugar.' },
          { name: 'Lalo!',               note: 'Desayuno y comida casuales, con producto de mercado.' },
        ]},
        { id: 'culture',   icon: 'landmark', label: 'Quiero cultura',         title: 'Para la cultura', items: [
          { name: 'Museo Tamayo',        note: 'Arte contemporáneo, una hora fácil.' },
          { name: 'Casa Luis Barragán',  note: 'Reserva con semanas de anticipación, grupos pequeños con horario.' },
          { name: 'Kurimanzutto',        note: 'Una galería líder de arte contemporáneo, entrada gratuita.' },
        ]},
        { id: 'kids',      icon: 'baby',     label: 'Viajo con niños',        title: 'Con niños', items: [
          { name: 'Parque México',              note: 'Juegos infantiles y senderos amplios para piernitas pequeñas.' },
          { name: 'Papalote Museo del Niño',    note: 'Exhibiciones interactivas, llena fácilmente medio día.' },
          { name: 'Zoológico de Chapultepec',   note: 'Entrada gratuita, senderos con sombra, a un taxi corto.' },
        ]},
        { id: 'nightlife', icon: 'martini',  label: 'Quiero vida nocturna',   title: 'Para la noche', items: [
          { name: 'Licorería Limantour',  note: 'Coctelería de clase mundial, llega antes de las 9pm.' },
          { name: 'Departamento',         note: 'Rooftop, DJ en vivo, ambiente más animado.' },
          { name: 'Bar Federalista',      note: 'Enfocado en mezcal, relajado y sin pretensiones.' },
        ]},
        { id: 'hidden',    icon: 'compass',  label: 'Lugares escondidos',     title: 'Lugares escondidos', items: [
          { name: 'Mercado de Medellín',  note: 'Un mercado que pocos turistas encuentran, prueba los puestos caribeños.' },
          { name: 'Jardín Pushkin',       note: 'Un parque diminuto y tranquilo que la mayoría de las guías se saltan.' },
          { name: 'Café Nin',             note: 'Escondido, fácil de pasar de largo, vale la pena encontrarlo.' },
        ]},
        { id: 'short',     icon: 'clock',    label: 'Solo tengo unas horas',  title: 'Solo unas horas', items: [
          { name: 'Vuelta por Parque España',        note: '20 minutos, de principio a fin.' },
          { name: 'Cafebrería El Péndulo',           note: 'Café y libros, todo en un solo lugar.' },
          { name: 'Mirador Torre Latinoamericana',   note: 'Elevador rápido, vista inigualable.' },
        ]},
      ],
      closeLabel: 'Cerrar',
      todayDateLabel: 'Esta semana en la Ciudad de México',
      todayH2: 'Ahora mismo en la ciudad',
      weatherTemp: '24° / 14°',
      weatherBody: 'Parcialmente nublado, con probable lluvia por la tarde, lleva una capa ligera para la lluvia.',
      todayItems: [
        { tag: 'Esta semana',   title: 'Feria de las Culturas Amigas',                  body: 'Un festival cultural de verano en el Zócalo, durante todo el mes.' },
        { tag: 'Mercado',       title: 'Tianguis dominical, Mercado de Medellín',       body: 'El mercado semanal se extiende a la calle, ve con hambre.' },
        { tag: 'Música en vivo', title: 'Jazzatlán en la Fonoteca Nacional',            body: 'Sesiones de jazz en vivo gratuitas, a un taxi corto de {neighborhood}.' },
        { tag: 'Atardecer',     title: 'Mirador Torre Latinoamericana',                 body: 'Los cielos suelen despejarse después de la lluvia de la tarde, vale la pena el timing.' },
      ],
      expEyebrow: 'Experiencias',
      expH2: 'Vale la pena el tiempo',
      expLede: 'Una lista corta, a propósito.',
      experiences: [
        { id: 'exp-lucha',      title: 'Lucha libre en la Arena México',                    body: 'Ruidoso, inolvidable, e inconfundiblemente de la Ciudad de México.' },
        { id: 'exp-xochimilco', title: 'Tarde en trajinera, Xochimilco',                    body: 'Un paseo lento por los canales, ve entre semana para evitar las multitudes.' },
        { id: 'exp-frida',      title: 'Museo Frida Kahlo, entrada con horario',            body: 'Reserva con al menos dos semanas de anticipación, los boletos se agotan rápido.' },
        { id: 'exp-ballet',     title: 'Ballet Folklórico, Palacio de Bellas Artes',        body: 'Hora y media, dentro de uno de los edificios más hermosos de la ciudad.' },
      ],
      foodEyebrow: 'Comida',
      foodH2: 'Editorial, no interminable',
      foodLede: 'Una recomendación por antojo.',
      foodCollections: [
        { tag: 'Desayuno',      name: 'Panadería Rosetta',    note: 'Llega antes de que se acaben los panes de guayaba.' },
        { tag: 'Tacos',         name: 'El Vilsito',           note: 'Vulcanizadora de día, taquería de noche.' },
        { tag: 'Café',          name: 'Café Avellaneda',      note: 'De lote pequeño, sin prisa.' },
        { tag: 'Cocteles',      name: 'Licorería Limantour',  note: 'Consistentemente uno de los mejores bares del mundo.' },
        { tag: 'Alta cocina',   name: 'Quintonil',            note: 'Reserva con un mes de anticipación, vale la espera.' },
        { tag: 'Joya escondida', name: 'Café Nin',            note: 'Fácil de pasar de largo, difícil de olvidar.' },
      ],
      continueEyebrow: 'Más allá de esta estancia',
      continueH2: '¿Listo para explorar más allá de tu estancia?',
      continueLede: 'Arma un itinerario personalizado, hoteles, días y presupuesto, en menos de un minuto.',
      continueCta: 'Planifica mi próximo viaje →',
      discoverEyebrow: 'Descubre más',
      discoverH2: 'Lagomplan va más allá de esta ciudad',
      footer: 'lagomplan · experiencia de huésped',
      hostLetter: {
        eyebrow: 'Una carta de tu anfitrión',
        quote: 'La Ciudad de México no se visita, se recorre dos veces, y aún faltan calles.',
        body: 'Esta guía nació de una pregunta que nos hacen nuestros huéspedes cada semana: ¿a dónde voy hoy? No es una lista exhaustiva, es un recorte curado de lo que de verdad vale la pena. Cada recomendación la caminamos, la comimos y la comprobamos nosotros mismos.',
        roleLabel: 'Tu anfitrión',
      },
    },

    en: {
      navLabel: 'Guest Stay',
      heroEyebrow: 'Curated by {host} · Enhanced by Lagomplan',
      heroTitle: 'Welcome to Mexico City.',
      heroSub: 'Everything you need for your stay in {neighborhood}, prepared like a friend would prepare it, not a search engine.',
      beginExploring: 'Begin exploring',
      beforeEyebrow: 'Before you arrive',
      beforeH2: 'A calm start to your trip',
      beforeLede: 'The practical basics, so you can stop thinking about logistics the moment you land.',
      arrivalItems: [
        { icon: 'plane',     title: 'Airport',        body: 'Most flights land at AICM (Terminal 1 or 2). From there, an authorized airport taxi or Uber takes 30–45 min to {neighborhood}. We can also offer you private transportation.' },
        { icon: 'car',       title: 'Transportation', body: 'Use Uber or Didi, cheaper and safer than hailing on the street. The Metro is excellent if you\'re comfortable with crowds. Or if you\'d prefer, we can arrange transportation for you.' },
        { icon: 'cloudSun',  title: 'Weather',        body: 'July is rainy season, sunny mornings, brief afternoon showers. Pack layers and a light rain jacket.' },
        { icon: 'banknote',  title: 'Money',          body: 'Cards are widely accepted. Keep some pesos in cash for markets, tips, and street food. In restaurants, 10–15% is the recommended tip; round up for taxis and casual spots.' },
        { icon: 'wifi',      title: 'Connectivity',   body: 'An eSIM activates in minutes. ', link: { text: 'Get yours through Airalo here', href: 'https://airalo.tpm.li/xkRXTIKe', after: '. Wi-Fi is reliable at the property and most cafés.' } },
        { icon: 'shield',    title: 'Safety',         body: 'Standard city awareness applies, stick to rideshare apps at night and keep valuables out of sight.' },
        { icon: 'briefcase', title: 'Packing',        body: 'Comfortable walking shoes, one nice outfit for dinner, and a light layer for cooler evenings.' },
        { icon: 'droplet',   title: 'Tap water',      body: 'We recommend bottled or filtered water for drinking. It\'s safe for showering and brushing your teeth.' },
        { icon: 'moon',      title: 'Coming back late', body: 'Arrive whenever you like, no need to worry. Just come in quietly, it\'s a building with neighbors.' },
        { icon: 'parking',   title: 'Parking',        body: 'Street parking is limited in the area. We recommend arriving by Uber or Didi instead of bringing a car.' },
      ],
      neighborhoodEyebrow: 'Your neighborhood',
      neighborhoodH2Prefix: 'Life around ',
      neighborhoodLede: 'Everything\'s within a short walk. Here\'s what I\'d point you to if you asked me at breakfast.',
      openInMapsLabel: 'Open list in Maps',
      perfectDayEyebrow: 'A perfect day',
      perfectDayH2: 'If I had one day here',
      perfectDayLede: 'This is exactly what I\'d do, start to finish.',
      moodEyebrow: 'Explore by mood',
      moodH2: 'What are you in the mood for?',
      moodLede: 'Pick a feeling, not a category.',
      moods: [
        { id: 'hungry',    icon: 'utensils', label: "I'm hungry",          title: 'For when you\'re hungry', items: [
          { name: 'Contramar',           note: 'Seafood, no reservation needed for lunch.' },
          { name: 'Panadería Rosetta',   note: 'Pastries worth setting an alarm for.' },
          { name: 'Lalo!',               note: 'Casual, market-driven breakfast and lunch.' },
        ]},
        { id: 'culture',   icon: 'landmark', label: 'I want culture',      title: 'For culture', items: [
          { name: 'Museo Tamayo',        note: 'Contemporary art, an easy hour.' },
          { name: 'Casa Luis Barragán',  note: 'Book weeks ahead, small timed groups.' },
          { name: 'Kurimanzutto',        note: 'A leading contemporary gallery, free entry.' },
        ]},
        { id: 'kids',      icon: 'baby',     label: 'Traveling with kids', title: 'With kids', items: [
          { name: 'Parque México',              note: 'Playgrounds and wide open paths for little legs.' },
          { name: 'Papalote Museo del Niño',    note: 'Hands-on exhibits, easily fills half a day.' },
          { name: 'Chapultepec Zoo',            note: 'Free entry, shaded paths, a short taxi away.' },
        ]},
        { id: 'nightlife', icon: 'martini',  label: 'I want nightlife',    title: 'For the night', items: [
          { name: 'Licorería Limantour',  note: 'World-class cocktails, arrive before 9pm.' },
          { name: 'Departamento',         note: 'Rooftop, DJ sets, a livelier crowd.' },
          { name: 'Bar Federalista',      note: 'Mezcal-forward, low-key and unpretentious.' },
        ]},
        { id: 'hidden',    icon: 'compass',  label: 'Hidden places',       title: 'Hidden places', items: [
          { name: 'Mercado de Medellín',  note: 'A market few tourists find, try the Caribbean stalls.' },
          { name: 'Jardín Pushkin',       note: 'A tiny, quiet park most guidebooks skip.' },
          { name: 'Café Nin',             note: 'Tucked away, easy to miss, worth finding.' },
        ]},
        { id: 'short',     icon: 'clock',    label: 'Only a few hours',    title: 'A few hours only', items: [
          { name: 'Parque España loop',              note: '20 minutes, start to finish.' },
          { name: 'Cafebrería El Péndulo',           note: 'Coffee and browsing, all in one stop.' },
          { name: 'Mirador Torre Latinoamericana',   note: 'Quick elevator up, unbeatable view.' },
        ]},
      ],
      closeLabel: 'Close',
      todayDateLabel: 'This week in Mexico City',
      todayH2: 'Right now in the city',
      weatherTemp: '24° / 14°',
      weatherBody: 'Partly cloudy, afternoon showers likely, bring a light rain layer.',
      todayItems: [
        { tag: 'This week',   title: 'Feria de las Culturas Amigas',                 body: 'A summer cultural festival in the Zócalo, running through the month.' },
        { tag: 'Market',      title: 'Mercado de Medellín, Sunday tianguis',         body: 'The weekly outdoor market spills onto the street, go hungry.' },
        { tag: 'Live music',  title: 'Jazzatlán at Fonoteca Nacional',               body: 'Free live jazz sets, a short taxi from {neighborhood}.' },
        { tag: 'Sunset',      title: 'Mirador Torre Latinoamericana',                body: 'Clearest skies tend to follow the afternoon rain, worth timing for.' },
      ],
      expEyebrow: 'Experiences',
      expH2: 'Worth the time',
      expLede: 'A short list, on purpose.',
      experiences: [
        { id: 'exp-lucha',      title: 'Lucha libre at Arena México',                     body: 'Loud, unforgettable, and unmistakably Mexico City.' },
        { id: 'exp-xochimilco', title: 'Afternoon on a trajinera, Xochimilco',            body: 'A slow boat ride through the canals, go on a weekday to skip the crowds.' },
        { id: 'exp-frida',      title: 'Museo Frida Kahlo, timed entry',                  body: 'Book at least two weeks ahead, tickets sell out fast.' },
        { id: 'exp-ballet',     title: 'Ballet Folklórico, Palacio de Bellas Artes',      body: 'An hour and a half, inside one of the city\'s most beautiful buildings.' },
      ],
      foodEyebrow: 'Food',
      foodH2: 'Editorial, not endless',
      foodLede: 'One pick per craving.',
      foodCollections: [
        { tag: 'Breakfast',   name: 'Panadería Rosetta',    note: 'Get there before the guava rolls sell out.' },
        { tag: 'Tacos',       name: 'El Vilsito',           note: 'A tire shop by day, taquería by night.' },
        { tag: 'Coffee',      name: 'Café Avellaneda',      note: 'Small-batch, unhurried.' },
        { tag: 'Cocktails',   name: 'Licorería Limantour',  note: 'Consistently one of the world\'s best bars.' },
        { tag: 'Fine dining', name: 'Quintonil',            note: 'Book a month out, it\'s worth the wait.' },
        { tag: 'Hidden gem',  name: 'Café Nin',             note: 'Easy to walk past, hard to forget.' },
      ],
      continueEyebrow: 'Beyond this stay',
      continueH2: 'Ready to explore beyond your stay?',
      continueLede: 'Build a personalized itinerary, hotels, days, and a budget, in less than a minute.',
      continueCta: 'Plan my next trip →',
      discoverEyebrow: 'Discover more',
      discoverH2: 'Lagomplan goes further than this city',
      footer: 'lagomplan · guest stay experience',
      hostLetter: {
        eyebrow: 'A letter from your host',
        quote: 'Mexico City isn\'t visited, it\'s walked twice, and there are still streets left.',
        body: 'This guide came from a question our guests ask us every week: where do I go today? It isn\'t exhaustive, it\'s a curated cut of what\'s truly worth it. We walked, ate, and checked every recommendation ourselves.',
        roleLabel: 'Your host',
      },
    },
  },
}
