// content/guia/cities/cdmx.ts
//
// City layer for Mexico City. Reusable across partners. Copy ported verbatim
// from the exported design (prototypes/Guest Stay Experience Design). Do not
// rewrite — this is the approved bilingual copy.

import type { City } from '../types'

export const cdmx: City = {
  id: 'cdmx',
  heroImage: '/images/guia/cdmx-banner.jpg',
  neighborhoodOrder: ['Veracruz 85', 'Roma Norte', 'Condesa', 'Polanco', 'Centro'],

  neighborhoods: {
    'Veracruz 85': {
      name: 'Veracruz 85',
      tabLabel: { es: 'Tu casa', en: 'Your house' },
      mapUrl: 'https://maps.app.goo.gl/qQSdT8RVpHCzGpxi8',
      tagline: { es: 'A pasos de tu puerta', en: 'Steps from your door' },
      orientation: { es: 'Todo aquí está genuinamente a 10 minutos a pie de tu casa, sin matices, esta es la zona real.', en: 'Everything here is genuinely a 10-minute walk from your house, no hedging, this is the real thing.' },
      spots: {
        es: [
          { icon: 'coffee',     name: 'Quentin',      distance: 'Ámsterdam 67a',                    note: 'Café de especialidad, repostería y una pequeña zona para sentarte, con decoración cuidada, el favorito del barrio.' },
          { icon: 'utensilsSm', name: 'Maizajo',       distance: 'Fernando Montes de Oca 113',       note: 'Tortillería en funcionamiento abajo, restaurante formal arriba. Pide el suadero y el tamal de boda. La taquería es de pie, sin reservación; el comedor de arriba sí las toma.' },
          { icon: 'trees',      name: 'Parque España',  distance: 'Parque España',   note: 'A unas cuadras: la contraparte más chica y tranquila del Parque México, una vuelta para correr, tianguis los sábados y bancas que se mantienen en sombra casi todo el día.' },
          { icon: 'landmark',   name: 'Foro Shakespeare', distance: 'Zamora 7, esq. Veracruz',       note: 'Un teatro independiente activo desde 1982, el foro alternativo de la ciudad, en la esquina misma. Taquilla abre a las 5pm entre semana.' },
          { icon: 'basket',     name: 'Choza',          distance: 'Tenancingo 38',                    note: 'Tienda y cafetería de vida artesanal: cerámica, textiles y objetos hechos en colaboración con artesanos independientes; buen lugar para un café mientras curioseas.' },
          { icon: 'martini',    name: 'Antesala',       distance: 'Sinaloa 141, Roma Nte., entre Cozumel y Salamanca', note: 'Coctelería de precisión junto a Lorea, con barra a la vista de los mixólogos y sets en vinil; más tranquilo que la Roma de fin de semana. Abre de martes a sábado desde las 6 pm, unos 10 minutos caminando.' },
        ],
        en: [
          { icon: 'coffee',     name: 'Quentin',      distance: 'Ámsterdam 67a',                    note: 'Specialty coffee, baked goods, a small seating area with trendy decor, the neighborhood\'s go-to.' },
          { icon: 'utensilsSm', name: 'Maizajo',       distance: 'Fernando Montes de Oca 113',       note: 'A working tortillería downstairs, a proper restaurant upstairs. Order the suadero and the tamal de boda. Standing-room taquería, no reservations; the upstairs dining room does take them.' },
          { icon: 'trees',      name: 'Parque España',  distance: 'Parque España',   note: 'A few blocks over: a smaller, calmer counterpart to Parque México, a loop for running, a Saturday market, and benches that stay in the shade most of the day.' },
          { icon: 'landmark',   name: 'Foro Shakespeare', distance: 'Zamora 7, esq. Veracruz',       note: 'An independent theater running since 1982, Mexico City\'s own alternative stage, right on the corner. Box office opens at 5pm on weekdays.' },
          { icon: 'basket',     name: 'Choza',          distance: 'Tenancingo 38',                    note: 'A lifestyle shop and coffee counter: ceramics, textiles and objects made in collaboration with independent artisans; good for a coffee while you browse.' },
          { icon: 'martini',    name: 'Antesala',       distance: 'Sinaloa 141, Roma Nte., entre Cozumel y Salamanca', note: 'Precision cocktails next to Lorea, with a bar that puts you right beside the mixologists and vinyl DJ sets; calmer than weekend Roma. Open Tuesday–Saturday from 6 pm, about a 10-minute walk.' },
        ],
      },
    },

    'Roma Norte': {
      name: 'Roma Norte',
      mapUrl: 'https://maps.app.goo.gl/NM3HZoTVpWPuNagb9',
      tagline: { es: 'Café de especialidad, galerías pequeñas, vida de banqueta.', en: 'Specialty coffee, small galleries, sidewalk life.' },
      orientation: { es: 'Una de tus dos zonas más cercanas, la mayoría de estos lugares está a 10 minutos o menos a pie.', en: 'One of your two closest zones, most of these are a 10-minute walk or less.' },
      spots: {
        es: [
          { icon: 'coffee',     name: 'Panadería Gala',                    distance: 'Tonalá 143',        note: 'Pan y repostería recién horneados, una buena manera de empezar la mañana.' },
          { icon: 'utensilsSm', name: 'Contramar',                         distance: 'Durango 200',       note: 'Las tostadas de atún ya valen el viaje. No se necesita reservación en la comida.' },
          { icon: 'trees',      name: 'Plaza Río de Janeiro',              distance: 'Durango y Orizaba', note: 'Una plaza arbolada con la fuente del David, rodeada de cafés y casonas antiguas.' },
          { icon: 'landmark',   name: 'MODO, Museo del Objeto del Objeto', distance: 'Colima 145',        note: 'Diseño y vida cotidiana mexicana en una casona; una hora bien invertida. Cierra lunes.' },
          { icon: 'basket',     name: 'Librería El Péndulo',               distance: 'Álvaro Obregón 86',  note: 'Librería-café de dos pisos; la mesa de autores mexicanos es el souvenir que sí vas a usar.' },
          { icon: 'martini',    name: 'Licorería Limantour',               distance: 'Álvaro Obregón 106', note: 'Top del mundo en coctelería; entre semana antes de las 8 no hay fila.' },
        ],
        en: [
          { icon: 'coffee',     name: 'Panadería Gala',                    distance: 'Tonalá 143',         note: 'Fresh-baked bread and pastries, a good way to start the morning.' },
          { icon: 'utensilsSm', name: 'Contramar',                         distance: 'Durango 200',        note: 'The tuna tostadas alone are worth the trip. No reservations needed at lunch.' },
          { icon: 'trees',      name: 'Plaza Río de Janeiro',              distance: 'Durango y Orizaba',  note: 'A tree-lined square with the David fountain, ringed by cafés and old mansions.' },
          { icon: 'landmark',   name: 'MODO, Museo del Objeto del Objeto', distance: 'Colima 145',         note: 'Mexican design and everyday objects in a townhouse; a well-spent hour. Closed Mondays.' },
          { icon: 'basket',     name: 'Librería El Péndulo',               distance: 'Álvaro Obregón 86',  note: 'Two-story bookstore-café; the Mexican authors table is the souvenir you\'ll actually use.' },
          { icon: 'martini',    name: 'Licorería Limantour',               distance: 'Álvaro Obregón 106', note: 'World\'s-best-list cocktails; weekdays before 8 there\'s no line.' },
        ],
      },
    },

    'Condesa': {
      name: 'Condesa',
      mapUrl: 'https://maps.app.goo.gl/B8UA8SMys7ZPKSb17',
      tagline: { es: 'Art déco, parques circulares, mezcalerías de barrio.', en: 'Art deco, circular parks, neighborhood mezcal bars.' },
      orientation: { es: 'Una de tus dos zonas más cercanas, la mayoría de estos lugares está a 10 minutos o menos a pie.', en: 'One of your two closest zones, most of these are a 10-minute walk or less.' },
      spots: {
        es: [
          { icon: 'coffee',     name: 'Lardo',                                                     distance: 'Agustín Melgar 6',                  note: 'Panadería y bistró en una parada, perfecto para el desayuno.' },
          { icon: 'utensilsSm', name: 'Ciena',                                                      distance: 'Alfonso Reyes 101, esq. Tacámbaro', note: 'Cocina abierta y terraza que sirve todo el día: desayuno desde las 8, barra por la tarde, cena sin prisa. Llévate la galleta de chocolate con sal.' },
          { icon: 'trees',      name: 'Parque México',                                              distance: 'Av. México',                        note: 'El corazón verde de la colonia: anfiteatro, viveros y bancas art déco.' },
          { icon: 'landmark',   name: 'Centro Cultural Bella Época / Librería Rosario Castellanos', distance: 'Tamaulipas 202',                    note: 'Un cine art déco convertido en la librería techada más grande del país; abre diario hasta las 10 pm.' },
          { icon: 'basket',     name: 'Proyecto Rufina',                                            distance: 'Ámsterdam 133',                     note: 'Ropa y cerámica mexicana en fibras naturales, producción limitada; no venden en línea, solo aquí.' },
          { icon: 'martini',    name: 'La Botica Mezcalería',                                       distance: 'Campeche 396',                      note: 'La primera mezcalería de la Ciudad de México, abierta en 2005 en un local de doce metros cuadrados; barra sencilla, mezcales de productor pequeño.' },
        ],
        en: [
          { icon: 'coffee',     name: 'Lardo',                                                     distance: 'Agustín Melgar 6',                  note: 'Bakery and bistro in one stop, perfect for breakfast.' },
          { icon: 'utensilsSm', name: 'Ciena',                                                      distance: 'Alfonso Reyes 101, esq. Tacámbaro', note: 'Open kitchen and a terrace that serves all day: breakfast from 8, bar menu in the afternoon, unhurried dinner. Take the salted chocolate cookie to go.' },
          { icon: 'trees',      name: 'Parque México',                                              distance: 'Av. México',                        note: 'The green heart of the neighborhood: amphitheater, plant stalls, art deco benches.' },
          { icon: 'landmark',   name: 'Centro Cultural Bella Época / Librería Rosario Castellanos', distance: 'Tamaulipas 202',                    note: 'An art deco cinema turned the country\'s largest single-room bookstore; open daily until 10 pm.' },
          { icon: 'basket',     name: 'Proyecto Rufina',                                            distance: 'Ámsterdam 133',                     note: 'Mexican clothing and ceramics in natural fibers, small-batch; no online store, only in person.' },
          { icon: 'martini',    name: 'La Botica Mezcalería',                                       distance: 'Campeche 396',                      note: 'The city\'s first mezcalería, opened in 2005 in a twelve-square-meter room; a simple bar, small-producer mezcal.' },
        ],
      },
    },

    'Polanco': {
      name: 'Polanco',
      mapUrl: 'https://maps.app.goo.gl/5Dd2SJVxMeHhGrgm6',
      tagline: { es: 'Museos y el bosque urbano más grande de América Latina.', en: 'Museums, Latin America\'s largest urban forest.' },
      orientation: { es: 'Vale la pena el viaje, mejor con varias horas libres, no una visita rápida.', en: 'Worth the trip, best paired with a few hours, not a quick stop.' },
      spots: {
        es: [
          { icon: 'coffee',     name: 'ENO',             distance: 'Petrarca 258',        note: 'El café de Enrique Olvera: concha con nata y un espresso antes de los museos.' },
          { icon: 'utensilsSm', name: 'El Turix',        distance: 'Emilio Castelar 212', note: 'Cochinita pibil de barra, en efectivo y de pie; el contrapeso perfecto al Polanco de manteles.' },
          { icon: 'trees',      name: 'Parque Lincoln',  distance: 'Emilio Castelar 163', note: 'Pavorreales, el reloj y las mejores bancas para leer.' },
          { icon: 'landmark',   name: 'Soumaya + Jumex', distance: 'Plaza Carso',         note: 'Dos museos pared con pared: Soumaya gratis y abierto diario, Jumex de arte contemporáneo, cierra lunes. Un solo viaje, tres horas.' },
          { icon: 'basket',     name: 'LAGO',            distance: 'Av. Pdte. Masaryk 310', note: 'Diseño latinoamericano contemporáneo: ropa, joyería, cerámica y objetos de más de veinte países, todo curado bajo un mismo techo.' },
          { icon: 'martini',    name: 'Ticuchi',         distance: 'Petrarca 254',        note: 'La barra de agaves del equipo de Pujol, a la luz de velas; abre de martes a domingo, desde las 5:30.' },
        ],
        en: [
          { icon: 'coffee',     name: 'ENO',             distance: 'Petrarca 258',        note: 'Enrique Olvera\'s café: concha with cream and an espresso before the museums.' },
          { icon: 'utensilsSm', name: 'El Turix',        distance: 'Emilio Castelar 212', note: 'Counter-service cochinita pibil, cash and standing; the perfect counterweight to white-tablecloth Polanco.' },
          { icon: 'trees',      name: 'Parque Lincoln',  distance: 'Emilio Castelar 163', note: 'Peacocks, a bandstand, and the best benches for reading.' },
          { icon: 'landmark',   name: 'Soumaya + Jumex', distance: 'Plaza Carso',         note: 'Two museums wall to wall: Soumaya free and open daily, Jumex for contemporary art, closed Mondays. One trip, three hours.' },
          { icon: 'basket',     name: 'LAGO',            distance: 'Av. Pdte. Masaryk 310', note: 'Contemporary Latin American design: clothing, jewelry, ceramics and objects from over twenty countries, all curated under one roof.' },
          { icon: 'martini',    name: 'Ticuchi',         distance: 'Petrarca 254',        note: 'The Pujol team\'s agave bar, candlelit; Tuesday to Sunday, from 5:30 pm.' },
        ],
      },
    },

    'Centro': {
      name: 'Centro',
      mapUrl: 'https://maps.app.goo.gl/6GhN852dkHL2xBxP8',
      tagline: { es: 'Capas de historia, mercados, la ciudad más densa.', en: 'Layers of history, markets, the densest city.' },
      orientation: { es: 'El corazón histórico, planea medio día; el metro o un viaje en auto te dejan ahí fácilmente.', en: 'The historic core, plan half a day; the metro or a ride gets you there easily.' },
      spots: {
        es: [
          { icon: 'coffee',     name: 'Café de Tacuba',          distance: 'Tacuba 28',             note: 'Cocina mexicana en un salón de azulejos desde 1912; pide los tamales de la casa.' },
          { icon: 'utensilsSm', name: 'Azul Histórico',          distance: 'Isabel la Católica 30', note: 'Cocina mexicana de Ricardo Muñoz Zurita en el patio de un palacio del siglo XVII, entre árboles y lámparas colgantes. Desayuno diario de 9 a 12; comida y cena hasta las 11. Reserva, el patio se llena.' },
          { icon: 'trees',      name: 'Alameda Central',         distance: 'Junto a Bellas Artes',  note: 'El parque más antiguo de América, recién a un costado de Bellas Artes; crúzalo al atardecer.' },
          { icon: 'landmark',   name: 'Templo Mayor + Bellas Artes', distance: 'Centro Histórico, a pie', note: 'Los dos anclas del Centro, a 15 minutos a pie por Madero: Templo Mayor (el corazón mexica de Tenochtitlan, con el monolito de Coyolxauhqui) y el Palacio de Bellas Artes (cúpula art nouveau, murales de Rivera y Siqueiros). Ambos cierran lunes.' },
          { icon: 'basket',     name: 'Mercado de San Juan',     distance: 'Ernesto Pugibet 21', note: 'El mercado de los chefs: quesos importados con degustación, mariscos de ambas costas; ve en la mañana y pide la torta de jamón serrano.' },
          { icon: 'martini',    name: 'Bar La Ópera',            distance: '5 de Mayo 10', note: 'Una cantina de 1895 con techos dorados y un balazo de Pancho Villa aún incrustado en el techo; abre desde la 1 pm, domingos cierra a las 6.' },
        ],
        en: [
          { icon: 'coffee',     name: 'Café de Tacuba',          distance: 'Tacuba 28',             note: 'Mexican cooking in a tiled hall since 1912; order the house tamales.' },
          { icon: 'utensilsSm', name: 'Azul Histórico',          distance: 'Isabel la Católica 30', note: 'Ricardo Muñoz Zurita\'s Mexican cooking in the courtyard of a 17th-century palace, under trees and hanging lamps. Breakfast daily 9–12; lunch and dinner until 11. Book ahead, the patio fills up.' },
          { icon: 'trees',      name: 'Alameda Central',         distance: 'Next to Bellas Artes',  note: 'The oldest park in the Americas, right beside Bellas Artes; cross it at sunset.' },
          { icon: 'landmark',   name: 'Templo Mayor + Bellas Artes', distance: 'Centro Histórico, on foot', note: 'The two anchors of the Centro, a 15-minute walk apart along Madero: Templo Mayor (the Mexica heart of Tenochtitlan, with the Coyolxauhqui monolith) and Palacio de Bellas Artes (art nouveau dome, Rivera and Siqueiros murals). Both closed Mondays.' },
          { icon: 'basket',     name: 'Mercado de San Juan',     distance: 'Ernesto Pugibet 21', note: 'The chefs\' market: imported cheeses with free tastings, seafood from both coasts; go in the morning and order the jamón serrano torta.' },
          { icon: 'martini',    name: 'Bar La Ópera',            distance: '5 de Mayo 10', note: 'An 1895 cantina with gilded ceilings and Pancho Villa\'s bullet still lodged overhead; opens at 1 pm, Sundays until 6.' },
        ],
      },
    },
  },

  destinations: [
    { name: 'Oaxaca',                 photoUrl: '/images/guides/oaxaca.jpg' },
    { name: 'Tulum',                  photoUrl: '/images/guides/tulum.jpg' },
    { name: 'San Miguel de Allende',  photoUrl: '/images/guides/san-miguel-de-allende.jpg' },
    { name: 'Valle de Bravo',         photoUrl: '/images/guides/valle-de-bravo.jpg' },
    { name: 'Mérida',                 photoUrl: '/images/guides/merida.jpg' },
  ],

  itinerary: {
    es: {
      eyebrow: 'Itinerario',
      title: '48 horas',
      lede: 'Dos días, caminados y comprobados.',
      days: [
        {
          title: 'Día uno, Roma / Condesa',
          items: [
            { time: '08:30', text: 'Café y pan local en Gala Panadería o Rosetta.' },
            { time: '10:00', text: 'Caminata por Río de Janeiro y Parque México.' },
            { time: '13:30', text: 'Comida en Contramar (llega 1:30 o sufre).' },
            { time: '15:00', text: 'Galerías de Roma Norte, entrada libre casi siempre.' },
            { time: '19:30', text: 'Cena ligera o tacos La Once Mil y cocktail en Licorería Limantour.' },
          ],
          note: 'Si quieres ver lo que nunca habías visto, aventúrate a la lucha libre.',
        },
        {
          title: 'Día dos, Centro / Chapultepec',
          items: [
            { time: '09:00', text: 'Zócalo antes de que llegue el calor.' },
            { time: '10:30', text: 'Templo Mayor, Bellas Artes y alrededores a pie.' },
            { time: '13:00', text: 'Comida en Azul Histórico, patio colonial en el Centro.' },
            { time: '16:00', text: 'Bosque de Chapultepec y Museo Soumaya.' },
            { time: '20:00', text: 'Cena en Máximo Bistrot o Expendio de Maíz si quieres que te sorprendan.' },
          ],
        },
      ],
      mapsCta: 'Abre las 48 horas en Google Maps →',
      mapsUrl: 'https://maps.app.goo.gl/DKdbomh1dSeDQoND6',
    },
    en: {
      eyebrow: 'Itinerary',
      title: '48 hours',
      lede: 'Two days, walked and checked.',
      days: [
        {
          title: 'Day one, Roma / Condesa',
          items: [
            { time: '08:30', text: 'Coffee and local bread at Gala Panadería or Rosetta.' },
            { time: '10:00', text: 'A walk through Río de Janeiro and Parque México.' },
            { time: '13:30', text: 'Lunch at Contramar (arrive by 1:30 or suffer).' },
            { time: '15:00', text: 'Roma Norte galleries, free entry most of the time.' },
            { time: '19:30', text: 'A light dinner or tacos at La Once Mil, and a cocktail at Licorería Limantour.' },
          ],
          note: 'If you want to see something you never have, take a chance on lucha libre.',
        },
        {
          title: 'Day two, Centro / Chapultepec',
          items: [
            { time: '09:00', text: 'The Zócalo before the heat arrives.' },
            { time: '10:30', text: 'Templo Mayor, Bellas Artes, and the surroundings on foot.' },
            { time: '13:00', text: 'Lunch at Azul Histórico, a colonial courtyard in the Centro.' },
            { time: '16:00', text: 'Bosque de Chapultepec and Museo Soumaya.' },
            { time: '20:00', text: 'Dinner at Máximo Bistrot or Expendio de Maíz if you want to be surprised.' },
          ],
        },
      ],
      mapsCta: 'Open the 48 hours in Google Maps →',
      mapsUrl: 'https://maps.app.goo.gl/DKdbomh1dSeDQoND6',
    },
  },

  copy: {
    es: {
      navLabel: 'Tu estancia',
      heroEyebrow: 'Curado por {host} · Potenciado por Lagomplan',
      heroTitle: 'Bienvenido a la Ciudad de México.',
      heroSub: 'Todo lo que necesitas para tu estancia, preparado como lo haría un amigo, no un buscador.',
      beginExploring: 'Empezar a explorar',
      beforeEyebrow: 'Antes de llegar',
      beforeH2: 'Un inicio tranquilo para tu viaje',
      beforeLede: 'Lo básico y práctico, para que dejes de pensar en logística en cuanto aterrices.',
      arrivalItems: [
        { icon: 'plane',     title: 'Aeropuerto',      body: 'La mayoría de los vuelos llegan al AICM (Terminal 1 o 2). De ahí, un taxi autorizado o Uber tarda 30–45 min a {neighborhood}.' },
        { icon: 'car',       title: 'Transporte',      body: 'Usa Uber, más barato y seguro que parar un taxi en la calle. El Metro es excelente si te sientes cómodo entre multitudes. Para transporte privado, te recomendamos ', link: { text: 'Insider', href: "https://wa.me/525539149062?text=%C2%A1Hola!%20Me%20interesa%20reservar%20una%20experiencia%20de%20Insider%20en%20la%20Ciudad%20de%20M%C3%A9xico.", after: ', una opción segura para quienes buscan comodidad y un transporte confiable.' } },
        { icon: 'cloudSun',  title: 'Clima',           body: 'Templado todo el año, 18–25 °C. Las lluvias se concentran de junio a septiembre, casi siempre chubascos breves por la tarde. Lleva capas.' },
        { icon: 'banknote',  title: 'Dinero',          body: 'Las tarjetas se aceptan ampliamente. Lleva algo de efectivo en pesos para mercados, propinas y comida callejera. En restaurantes, la propina recomendada es 10–15%; redondea en taxis y puestos casuales.' },
        { icon: 'wifi',      title: 'Conectividad',    body: 'Un eSIM se activa en minutos. ', link: { text: 'Consigue el tuyo con Airalo aquí', href: 'https://airalo.tpm.li/xkRXTIKe', after: '. El wifi es confiable en la propiedad y en la mayoría de los cafés.' } },
        { icon: 'shield',    title: 'Seguridad',       body: 'Aplica el sentido común habitual en ciudad, usa apps de transporte por la noche y mantén tus objetos de valor fuera de vista. En una emergencia, el 911 funciona en todo el país.' },
        { icon: 'briefcase', title: 'Equipaje',        body: 'Zapatos cómodos para caminar, ropa casual, y una capa ligera para las noches frescas.' },
        { icon: 'droplet',   title: 'Agua de la llave', body: 'Te recomendamos no tomar agua de la llave, es segura para bañarte, lavarte los dientes y lavar trastes. Si tu departamento cuenta con agua purificada, estará señalada claramente; si tienes duda, mejor usa agua embotellada.' },
        { icon: 'moon',      title: 'Llegar tarde',    body: 'Llega a la hora que sea, no hay problema.' },
        { icon: 'parking',   title: 'Estacionamiento', body: 'El estacionamiento en la calle es limitado en la zona. Te recomendamos llegar en Uber o Didi en vez de traer coche.' },
        { icon: 'mountain',  title: 'Altitud',         body: 'La Ciudad de México está a 2,240 msnm. Toma más agua de lo habitual, ve con calma con el alcohol la primera noche, y evita planear una caminata exigente o una noche larga el primer día; la mayoría se adapta en 24–48 horas.' },
        { icon: 'cross',     title: 'Salud y farmacias', body: 'Las farmacias (del Ahorro, Guadalajara) están por todas partes, muchas abren 24 horas, y venden medicamentos comunes sin receta. Para algo más, pide a tu anfitrión una clínica cercana; el 911 es solo para emergencias.' },
      ],
      neighborhoodEyebrow: 'Zonas de la ciudad',
      neighborhoodH2: 'Cinco zonas, cinco maneras de vivir la ciudad',
      openInMapsLabel: 'Ver lista en Maps',
      mapCardPrimary: 'Ver los {n} lugares en el mapa',
      mapCardSecondary: 'Lista de Google Maps',
      moodEyebrow: 'Explora según tu ánimo',
      moodH2: '¿Qué se te antoja hoy?',
      moodLede: 'Elige un ánimo, no una categoría.',
      moods: [
        { id: 'hungry',    icon: 'utensils', label: 'Tengo hambre',          title: 'Para cuando tienes hambre', items: [
          { name: 'Lalo!',               note: 'Desayuno y comida casuales, con producto de mercado.' },
          { name: 'Masala y Maíz',       note: 'Cruce de México, India y África Oriental; reserva con antelación.' },
          { name: 'Taquería Orinoco',    note: 'Tacos norteños hasta la madrugada; el trompo y el chicharrón, sin falta.' },
        ]},
        { id: 'culture',   icon: 'landmark', label: 'Quiero cultura',         title: 'Para la cultura', items: [
          { name: 'Museo Tamayo',        note: 'Arte contemporáneo, una hora fácil.' },
          { name: 'Casa Luis Barragán',  note: 'Reserva con semanas de anticipación, grupos pequeños con horario.' },
          { name: 'Kurimanzutto',        note: 'Una galería líder de arte contemporáneo, entrada gratuita.' },
        ]},
        { id: 'kids',      icon: 'baby',     label: 'Viajo con niños',        title: 'Con niños', items: [
          { name: 'Parque México',              note: 'Juegos infantiles y senderos amplios para piernitas pequeñas.' },
          { name: 'Papalote Museo del Niño',    note: 'Exhibiciones interactivas, llena fácilmente medio día.' },
          { name: 'Zoológico de Chapultepec',   note: 'Entrada gratuita, senderos con sombra, a un taxi corto.' },
        ]},
        { id: 'nightlife', icon: 'martini',  label: 'Quiero vida nocturna',   title: 'Para la noche', items: [
          { name: 'Licorería Limantour',  note: 'Coctelería de clase mundial, llega antes de las 9pm.' },
          { name: 'Departamento',         note: 'Rooftop, DJ en vivo, ambiente más animado.' },
          { name: 'Bar Federalista',      note: 'Enfocado en mezcal, relajado y sin pretensiones.' },
        ]},
        { id: 'hidden',    icon: 'compass',  label: 'Lugares escondidos',     title: 'Lugares escondidos', items: [
          { name: 'Foro Shakespeare',     note: 'Un pequeño teatro-bar independiente en una casa reconvertida; la mayoría pasa de largo.' },
          { name: 'Bósforo',              note: 'Una mezcalería detrás de una puerta sin letrero; busca las luces de foquitos.' },
          { name: 'Casa Franca',          note: 'Una casa reconvertida en librería-café; fácil de pasar de largo.' },
        ]},
        { id: 'short',     icon: 'clock',    label: 'Solo tengo unas horas',  title: 'Solo unas horas', items: [
          { name: 'Vuelta por Parque España',        note: '20 minutos, de principio a fin.' },
          { name: 'Cafebrería El Péndulo',           note: 'Café y libros, todo en un solo lugar.' },
          { name: 'Mirador Torre Latinoamericana',   note: 'Elevador rápido, vista inigualable.' },
        ]},
      ],
      closeLabel: 'Cerrar',
      todayDateLabel: 'Los ritmos de la ciudad',
      todayH2: 'Cada semana en la ciudad',
      weatherTemp: '24° / 14°',
      weatherBody: 'Parcialmente nublado, con probable lluvia por la tarde, lleva una capa ligera para la lluvia.',
      todayItems: [
        { tag: 'Domingo',           title: 'Muévete en Bici, Reforma',       body: 'Cada domingo de 8 a 2, Reforma cierra a los coches: ciclistas, corredores y préstamo gratuito de bicis. La ciudad en su mejor humor.' },
        { tag: 'Martes y viernes',  title: 'Lucha libre, Arena México',      body: 'Martes popular a las 7:30, viernes espectacular a las 8:30, el viernes es el cartel grande. Taquilla abre a las 5.' },
        { tag: 'Sábado',            title: 'Bazar Sábado, San Ángel',        body: 'Solo sábados: arte y artesanía en una plaza colonial empedrada; medio día completo, comida incluida.' },
        { tag: 'Atardecer',         title: 'Mirador Torre Latinoamericana',  body: 'Los cielos suelen despejarse después de la lluvia de la tarde, vale la pena el timing.' },
      ],
      expEyebrow: 'Experiencias',
      expH2: 'Vale la pena el tiempo',
      expLede: 'Una lista corta, a propósito.',
      expPartnerNote: 'Reservadas a través de Insider, nuestro partner local.',
      expBookCta: 'Reservar por WhatsApp',
      expDetailsCta: 'Detalles',
      expDescriptionLabel: 'Descripción',
      expHowToBookLabel: 'Cómo reservar',
      expMinTimeLabel: 'Tiempo mínimo de reservación',
      experiences: [
        {
          id: 'exp-teotihuacan',
          title: 'Teotihuacán: más allá de las Pirámides',
          teaser: 'Guía privado, a tu ritmo, más allá de la visita típica.',
          description: 'Descubre Teotihuacán más allá de la visita típica. Explora uno de los sitios arqueológicos más impresionantes de México con un guía privado y vive su historia a tu propio ritmo. Cada itinerario se diseña a la medida de tus intereses, para una visita más personal y significativa.',
          howToBookLinkText: 'Escríbenos por WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=%C2%A1Hola!%20Me%20interesa%20reservar%20una%20experiencia%20de%20Insider%20en%20la%20Ciudad%20de%20M%C3%A9xico.",
          howToBook: ' con tu fecha preferida, número de huéspedes y hotel. Confirmaremos disponibilidad, personalizaremos tu experiencia y nos encargaremos de todas las reservaciones.',
          minBookingTime: '48 horas de anticipación.',
          needSoonerNote: '¿Lo necesitas antes? Escríbenos. Siempre intentaremos hacerlo posible si hay disponibilidad.',
        },
        {
          id: 'exp-lucha',
          title: 'Lucha libre en Arena México',
          teaser: 'Cata de mezcal, luego máscaras, acrobacias y ambiente eléctrico.',
          description: 'Vive una de las tradiciones más icónicas de la Ciudad de México. Comienza la noche con una cata de mezcal antes de dirigirte a la Arena México para una noche inolvidable de máscaras, acrobacias y ambiente eléctrico. Te ayudamos a elegir la opción de asientos que mejor se adapte a tu experiencia.',
          howToBookLinkText: 'Escríbenos por WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=%C2%A1Hola!%20Me%20interesa%20reservar%20una%20experiencia%20de%20Insider%20en%20la%20Ciudad%20de%20M%C3%A9xico.",
          howToBook: ' con tu fecha preferida, número de huéspedes y hotel. Confirmaremos disponibilidad, personalizaremos tu experiencia y nos encargaremos de todas las reservaciones.',
          minBookingTime: '3 días de anticipación.',
          needSoonerNote: '¿Lo necesitas antes? Escríbenos. Siempre intentaremos hacerlo posible si hay disponibilidad.',
        },
        {
          id: 'exp-frida',
          title: 'Frida Kahlo y Coyoacán',
          teaser: 'Casa Azul, Anahuacalli y las calles bohemias de Coyoacán.',
          description: [
            'Descubre uno de los barrios más encantadores de la Ciudad de México a través de sus calles llenas de color, plazas históricas y cafés locales.',
            'Cuando hay disponibilidad, tu experiencia incluye la entrada al Museo Frida Kahlo (Casa Azul). Tu boleto también da acceso al Museo Anahuacalli, la extraordinaria obra arquitectónica de Diego Rivera y uno de nuestros museos de arte favoritos en la Ciudad de México, una experiencia que recomendamos ampliamente.',
            'Si los boletos de Casa Azul no están disponibles, diseñaremos un itinerario alternativo que incluye la Casa Roja, el hogar donde después vivieron los padres y la hermana de Frida Kahlo, junto con otros puntos culturales que capturan el espíritu de Coyoacán.',
          ],
          howToBookLinkText: 'Escríbenos por WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=%C2%A1Hola!%20Me%20interesa%20reservar%20una%20experiencia%20de%20Insider%20en%20la%20Ciudad%20de%20M%C3%A9xico.",
          howToBook: ' con tu fecha preferida, número de huéspedes y hotel. Confirmaremos disponibilidad, personalizaremos tu experiencia y nos encargaremos de todas las reservaciones.',
          minBookingTime: [
            'Con Museo Frida Kahlo (Casa Azul): recomendamos reservar de 3 a 6 semanas antes, ya que los boletos se agotan rápido.',
            'Itinerario alternativo: 3 días de anticipación.',
          ],
          needSoonerNote: '¿Lo necesitas antes? Escríbenos. Siempre intentaremos hacerlo posible si hay disponibilidad.',
        },
        {
          id: 'exp-tacos',
          title: 'La Ciudad de México a través de sus tacos',
          teaser: 'Un recorrido curado por las mejores taquerías de barrio.',
          description: 'Descubre la Ciudad de México a través de una de sus más grandes tradiciones culinarias. Visita una selección cuidadosamente curada de taquerías de barrio, probando una variedad de los tacos más icónicos de México junto con bebidas tradicionales locales, mientras conoces las historias, técnicas y tradiciones que han dado forma a la vibrante cultura callejera de la ciudad. Diseñada para viajeros curiosos y amantes de la comida por igual, esta experiencia ofrece una introducción auténtica a una de las tradiciones más queridas de la Ciudad de México.',
          howToBookLinkText: 'Escríbenos por WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=%C2%A1Hola!%20Me%20interesa%20reservar%20una%20experiencia%20de%20Insider%20en%20la%20Ciudad%20de%20M%C3%A9xico.",
          howToBook: ' con tu fecha preferida, número de huéspedes y hotel. Confirmaremos disponibilidad, personalizaremos tu experiencia y nos encargaremos de todas las reservaciones.',
          minBookingTime: '3 días de anticipación.',
          needSoonerNote: '¿Lo necesitas antes? Escríbenos. Siempre intentaremos hacerlo posible si hay disponibilidad.',
        },
        {
          id: 'exp-own-plan',
          title: 'Tu propio plan',
          teaser: '¿Algo distinto en mente? Armamos tu plan a la medida.',
          description: '¿Buscas algo que no está en esta lista? Cuéntanos qué te gustaría hacer, desde otro sitio arqueológico hasta una experiencia más privada o fuera de lo común, y lo armamos contigo, con el mismo cuidado que el resto de nuestras experiencias.',
          howToBookLinkText: 'Escríbenos por WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=%C2%A1Hola!%20Me%20interesa%20reservar%20una%20experiencia%20de%20Insider%20en%20la%20Ciudad%20de%20M%C3%A9xico.",
          howToBook: ' contándonos qué te gustaría hacer, tu fecha preferida, número de huéspedes y hotel. Te responderemos con opciones y disponibilidad.',
          minBookingTime: 'Varía según la experiencia, te lo confirmamos al escribirnos.',
        },
      ],
      foodEyebrow: 'Comida',
      foodH2: 'Los imperdibles',
      foodLede: 'Una recomendación por antojo.',
      foodCollections: [
        { tag: 'Desayuno',      name: 'Panadería Rosetta',    note: 'Llega antes de que se acaben los panes de guayaba.' },
        { tag: 'Tacos',         name: 'El Vilsito',           note: 'Vulcanizadora de día, taquería de noche.' },
        { tag: 'Café',          name: 'Café Avellaneda',      note: 'De lote pequeño, sin prisa.' },
        { tag: 'Cocteles',      name: 'Licorería Limantour',  note: 'Consistentemente uno de los mejores bares del mundo.' },
        { tag: 'Alta cocina',   name: 'Quintonil',            note: 'Reserva con un mes de anticipación, vale la espera.' },
        { tag: 'Joya escondida', name: 'Café Nin',            note: 'Fácil de pasar de largo, difícil de olvidar.' },
        { tag: 'Antojitos',     name: 'El Turix',            note: 'Cochinita pibil de las de siempre en Polanco; solo efectivo y hasta que se acaba.' },
        { tag: 'Postre',        name: 'Nevería Roxy',        note: 'Nieves de garrafa desde 1946, la de mamey no falla.' },
      ],
      continueEyebrow: 'Más allá de esta estancia',
      continueH2: '¿Listo para explorar más allá de tu estancia?',
      continueLede: 'Arma un itinerario personalizado, hoteles, días y presupuesto, en menos de un minuto.',
      continueCta: 'Planifica mi próximo viaje →',
      stickyCta: 'Personalizar mi viaje en 60 segundos',
      newsletterTitle: 'El Itinerario',
      newsletterBody: 'Esta ciudad cambia cada quincena. El Itinerario te la manda, una guía nueva y un destino que no tenías en el radar, dos veces al mes.',
      newsletterPlaceholder: 'tu@correo.com',
      newsletterCta: 'Suscribirme',
      newsletterFinePrint: 'Cada 15 días · En español · Sin spam',
      discoverEyebrow: 'Descubre más',
      discoverH2: 'Lagomplan va más allá de esta ciudad',
      footer: 'lagomplan · experiencia de huésped',
      hostLetter: {
        eyebrow: 'Una carta de tu anfitrión',
        quote: 'La Ciudad de México no se visita, se recorre dos veces, y aún faltan calles.',
        body: 'Esta guía nació de una pregunta que nos hacen nuestros huéspedes cada semana: ¿a dónde voy hoy? No es una lista exhaustiva, es un recorte curado de lo que de verdad vale la pena. Cada recomendación la caminamos, la comimos y la comprobamos nosotros mismos.',
        roleLabel: 'Tu anfitrión',
      },
    },

    en: {
      navLabel: 'Guest Stay',
      heroEyebrow: 'Curated by {host} · Enhanced by Lagomplan',
      heroTitle: 'Welcome to Mexico City.',
      heroSub: 'Everything you need for your stay, prepared like a friend would prepare it, not a search engine.',
      beginExploring: 'Begin exploring',
      beforeEyebrow: 'Before you arrive',
      beforeH2: 'A calm start to your trip',
      beforeLede: 'The practical basics, so you can stop thinking about logistics the moment you land.',
      arrivalItems: [
        { icon: 'plane',     title: 'Airport',        body: 'Most flights land at AICM (Terminal 1 or 2). From there, an authorized airport taxi or Uber takes 30–45 min to {neighborhood}.' },
        { icon: 'car',       title: 'Transportation', body: "Use Uber, cheaper and safer than hailing on the street. The Metro is excellent if you're comfortable with crowds. For private transportation, we recommend ", link: { text: 'Insider', href: "https://wa.me/525539149062?text=Hello!%20I'm%20interested%20in%20booking%20an%20Insider%20Mexico%20City%20experience.", after: ', a safe option for you looking for comfort, and reliable transport.' } },
        { icon: 'cloudSun',  title: 'Weather',        body: 'Mild year-round, 18–25 °C. Rain concentrates June–September, mostly brief afternoon showers. Pack layers.' },
        { icon: 'banknote',  title: 'Money',          body: 'Cards are widely accepted. Keep some pesos in cash for markets, tips, and street food. In restaurants, 10–15% is the recommended tip; round up for taxis and casual spots.' },
        { icon: 'wifi',      title: 'Connectivity',   body: 'An eSIM activates in minutes. ', link: { text: 'Get yours through Airalo here', href: 'https://airalo.tpm.li/xkRXTIKe', after: '. Wi-Fi is reliable at the property and most cafés.' } },
        { icon: 'shield',    title: 'Safety',         body: 'Standard city awareness applies, stick to rideshare apps at night and keep valuables out of sight. In an emergency, 911 works citywide.' },
        { icon: 'briefcase', title: 'Packing',        body: 'Comfortable walking shoes, casual clothes, and a light layer for cooler evenings.' },
        { icon: 'droplet',   title: 'Tap water',      body: "Please don't drink the tap water, it's fine for showering, brushing your teeth, and washing dishes. If your unit has purified water available, it will be clearly marked; when in doubt, stick to bottled." },
        { icon: 'moon',      title: 'Coming back late', body: 'Arrive whenever you like, no need to worry.' },
        { icon: 'parking',   title: 'Parking',        body: 'Street parking is limited in the area. We recommend arriving by Uber or Didi instead of bringing a car.' },
        { icon: 'mountain',  title: 'Altitude',       body: "Mexico City sits at 2,240m (7,350 ft). Drink more water than usual, go easy on alcohol the first night, and don't schedule a hard hike or a big night out on day one; most people adjust within 24–48 hours." },
        { icon: 'cross',     title: 'Health & Pharmacies', body: 'Pharmacies (Farmacias del Ahorro, Guadalajara) are everywhere, many open 24 hours, and sell common medications over the counter. For anything more, ask your host for a nearby clinic; 911 is for emergencies only.' },
      ],
      neighborhoodEyebrow: 'City zones',
      neighborhoodH2: 'Five zones, five ways to experience the city',
      openInMapsLabel: 'Open list in Maps',
      mapCardPrimary: 'See all {n} places on the map',
      mapCardSecondary: 'Google Maps list',
      moodEyebrow: 'Explore by mood',
      moodH2: 'What are you in the mood for?',
      moodLede: 'Pick a feeling, not a category.',
      moods: [
        { id: 'hungry',    icon: 'utensils', label: "I'm hungry",          title: 'For when you\'re hungry', items: [
          { name: 'Lalo!',               note: 'Casual, market-driven breakfast and lunch.' },
          { name: 'Masala y Maíz',       note: 'Mexico meets India and East Africa; book ahead.' },
          { name: 'Taquería Orinoco',    note: 'Norteño-style tacos into the early hours; go for the trompo and chicharrón.' },
        ]},
        { id: 'culture',   icon: 'landmark', label: 'I want culture',      title: 'For culture', items: [
          { name: 'Museo Tamayo',        note: 'Contemporary art, an easy hour.' },
          { name: 'Casa Luis Barragán',  note: 'Book weeks ahead, small timed groups.' },
          { name: 'Kurimanzutto',        note: 'A leading contemporary gallery, free entry.' },
        ]},
        { id: 'kids',      icon: 'baby',     label: 'Traveling with kids', title: 'With kids', items: [
          { name: 'Parque México',              note: 'Playgrounds and wide open paths for little legs.' },
          { name: 'Papalote Museo del Niño',    note: 'Hands-on exhibits, easily fills half a day.' },
          { name: 'Chapultepec Zoo',            note: 'Free entry, shaded paths, a short taxi away.' },
        ]},
        { id: 'nightlife', icon: 'martini',  label: 'I want nightlife',    title: 'For the night', items: [
          { name: 'Licorería Limantour',  note: 'World-class cocktails, arrive before 9pm.' },
          { name: 'Departamento',         note: 'Rooftop, DJ sets, a livelier crowd.' },
          { name: 'Bar Federalista',      note: 'Mezcal-forward, low-key and unpretentious.' },
        ]},
        { id: 'hidden',    icon: 'compass',  label: 'Hidden places',       title: 'Hidden places', items: [
          { name: 'Foro Shakespeare',     note: 'A small independent theater-bar in a converted house, most guests walk right past it.' },
          { name: 'Bósforo',              note: 'A mezcal bar behind an unmarked door, look for the string lights.' },
          { name: 'Casa Franca',          note: 'A converted house turned bookstore-café, easy to walk past.' },
        ]},
        { id: 'short',     icon: 'clock',    label: 'Only a few hours',    title: 'A few hours only', items: [
          { name: 'Parque España loop',              note: '20 minutes, start to finish.' },
          { name: 'Cafebrería El Péndulo',           note: 'Coffee and browsing, all in one stop.' },
          { name: 'Mirador Torre Latinoamericana',   note: 'Quick elevator up, unbeatable view.' },
        ]},
      ],
      closeLabel: 'Close',
      todayDateLabel: "The city's weekly rhythm",
      todayH2: 'Every week in Mexico City',
      weatherTemp: '24° / 14°',
      weatherBody: 'Partly cloudy, afternoon showers likely, bring a light rain layer.',
      todayItems: [
        { tag: 'Sunday',        title: 'Muévete en Bici, Reforma',       body: 'Every Sunday 8am–2pm, Reforma closes to cars for cyclists, runners and free bike loans. The city in its best mood.' },
        { tag: 'Tues & Fri',    title: 'Lucha libre, Arena México',      body: 'Tuesday popular at 7:30, Friday spectacular at 8:30, Friday has the bigger card. Box office opens at 5.' },
        { tag: 'Saturday',      title: 'Bazar Sábado, San Ángel',        body: 'Saturdays only: art and crafts in a cobblestone colonial plaza, a full half-day, lunch included.' },
        { tag: 'Sunset',        title: 'Mirador Torre Latinoamericana',  body: 'Clearest skies tend to follow the afternoon rain, worth timing for.' },
      ],
      expEyebrow: 'Experiences',
      expH2: 'Worth the time',
      expLede: 'A short list, on purpose.',
      expPartnerNote: 'Booked through Insider, our local partner.',
      expBookCta: 'Book via WhatsApp',
      expDetailsCta: 'Details',
      expDescriptionLabel: 'Description',
      expHowToBookLabel: 'How to book',
      expMinTimeLabel: 'Minimum booking time',
      experiences: [
        {
          id: 'exp-teotihuacan',
          title: 'Teotihuacán: Beyond the Pyramids',
          teaser: 'Private guide, your own pace, beyond the typical visit.',
          description: "Discover Teotihuacán beyond the typical visit. Explore one of Mexico's most impressive archaeological sites with a private guide and experience its history at your own pace. Every itinerary is thoughtfully curated to match your interests, creating a more personal and meaningful visit.",
          howToBookLinkText: 'Contact us via WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=Hello!%20I'm%20interested%20in%20booking%20an%20Insider%20Mexico%20City%20experience.",
          howToBook: " with your preferred date, number of guests and hotel. We'll confirm availability, personalize your experience and take care of all reservations.",
          minBookingTime: '48 hours in advance.',
          needSoonerNote: "Need it sooner? Reach out to us. We'll always try to make it happen if availability allows.",
        },
        {
          id: 'exp-lucha',
          title: 'Lucha Libre at Arena México',
          teaser: 'Mezcal tasting, then masks, acrobatics and electric atmosphere.',
          description: "Experience one of Mexico City's most iconic traditions. Start the evening with a mezcal tasting before heading to Arena México for an unforgettable night of masks, acrobatics and electric atmosphere. We'll help you choose the seating option that best fits your experience.",
          howToBookLinkText: 'Contact us via WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=Hello!%20I'm%20interested%20in%20booking%20an%20Insider%20Mexico%20City%20experience.",
          howToBook: " with your preferred date, number of guests and hotel. We'll confirm availability, personalize your experience and take care of all reservations.",
          minBookingTime: '3 days in advance.',
          needSoonerNote: "Need it sooner? Reach out to us. We'll always try to make it happen if availability allows.",
        },
        {
          id: 'exp-frida',
          title: 'Frida Kahlo & Coyoacán',
          teaser: "Casa Azul, Anahuacalli, and Coyoacán's bohemian streets.",
          description: [
            "Discover one of Mexico City's most charming neighborhoods through its colorful streets, historic plazas and local cafés.",
            "When available, your experience includes admission to the Frida Kahlo Museum (Casa Azul). Your ticket also includes access to the Anahuacalli Museum, Diego Rivera's extraordinary architectural masterpiece and one of our favorite art museums in Mexico City, an experience we highly recommend.",
            "If Casa Azul tickets are unavailable, we'll curate an alternative itinerary featuring Casa Roja, the home where Frida Kahlo's parents and sister later lived, along with other cultural highlights that capture the spirit of Coyoacán.",
          ],
          howToBookLinkText: 'Contact us via WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=Hello!%20I'm%20interested%20in%20booking%20an%20Insider%20Mexico%20City%20experience.",
          howToBook: " with your preferred date, number of guests and hotel. We'll confirm availability, personalize your experience and take care of all reservations.",
          minBookingTime: [
            'With Frida Kahlo Museum (Casa Azul): We recommend booking 3–6 weeks in advance, as tickets sell out quickly.',
            'Alternative itinerary: 3 days in advance.',
          ],
          needSoonerNote: "Need it sooner? Reach out to us. We'll always try to make it happen if availability allows.",
        },
        {
          id: 'exp-tacos',
          title: 'Mexico City Through Tacos',
          teaser: "A curated crawl through the city's best neighborhood taquerías.",
          description: "Discover Mexico City through one of its greatest culinary traditions. Visit a carefully curated selection of neighborhood taquerías, tasting a variety of Mexico's most iconic tacos alongside traditional local drinks, while learning about the stories, techniques and traditions that have shaped the city's vibrant street food culture. Designed for curious travelers and food lovers alike, this experience offers an authentic introduction to one of Mexico City's most beloved traditions.",
          howToBookLinkText: 'Contact us via WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=Hello!%20I'm%20interested%20in%20booking%20an%20Insider%20Mexico%20City%20experience.",
          howToBook: " with your preferred date, number of guests and hotel. We'll confirm availability, personalize your experience and take care of all reservations.",
          minBookingTime: '3 days in advance.',
          needSoonerNote: "Need it sooner? Reach out to us. We'll always try to make it happen if availability allows.",
        },
        {
          id: 'exp-own-plan',
          title: 'Your Own Plan',
          teaser: "Something else in mind? We'll build it around you.",
          description: "Looking for something that's not on this list? Tell us what you'd like to do, from another archaeological site to something more private or off the beaten path, and we'll build it with you, with the same care as our other experiences.",
          howToBookLinkText: 'Message us on WhatsApp',
          howToBookLinkHref: "https://wa.me/525539149062?text=Hello!%20I'm%20interested%20in%20booking%20an%20Insider%20Mexico%20City%20experience.",
          howToBook: " with what you'd like to do, your preferred date, number of guests and hotel. We'll get back to you with options and availability.",
          minBookingTime: "Varies by experience, we'll confirm once you reach out.",
        },
      ],
      foodEyebrow: 'Food',
      foodH2: 'The must-sees',
      foodLede: 'One pick per craving.',
      foodCollections: [
        { tag: 'Breakfast',   name: 'Panadería Rosetta',    note: 'Get there before the guava rolls sell out.' },
        { tag: 'Tacos',       name: 'El Vilsito',           note: 'A tire shop by day, taquería by night.' },
        { tag: 'Coffee',      name: 'Café Avellaneda',      note: 'Small-batch, unhurried.' },
        { tag: 'Cocktails',   name: 'Licorería Limantour',  note: 'Consistently one of the world\'s best bars.' },
        { tag: 'Fine dining', name: 'Quintonil',            note: 'Book a month out, it\'s worth the wait.' },
        { tag: 'Hidden gem',  name: 'Café Nin',             note: 'Easy to walk past, hard to forget.' },
        { tag: 'Street snacks', name: 'El Turix',           note: 'Old-school cochinita pibil in Polanco; cash only, and only until it runs out.' },
        { tag: 'Dessert',       name: 'Nevería Roxy',        note: 'Churned ice cream since 1946, the mamey never misses.' },
      ],
      continueEyebrow: 'Beyond this stay',
      continueH2: 'Ready to explore beyond your stay?',
      continueLede: 'Build a personalized itinerary, hotels, days, and a budget, in less than a minute.',
      continueCta: 'Plan my next trip →',
      stickyCta: 'Personalize my trip in 60 seconds',
      newsletterTitle: 'El Itinerario',
      newsletterBody: 'This city changes every two weeks. El Itinerario delivers it, a new guide and a destination you didn\'t have on your radar, twice a month.',
      newsletterPlaceholder: 'you@email.com',
      newsletterCta: 'Subscribe',
      newsletterFinePrint: 'Every two weeks · In Spanish · No spam',
      discoverEyebrow: 'Discover more',
      discoverH2: 'Lagomplan goes further than this city',
      footer: 'lagomplan · guest stay experience',
      hostLetter: {
        eyebrow: 'A letter from your host',
        quote: 'Mexico City isn\'t visited, it\'s walked twice, and there are still streets left.',
        body: 'This guide came from a question our guests ask us every week: where do I go today? It isn\'t exhaustive, it\'s a curated cut of what\'s truly worth it. We walked, ate, and checked every recommendation ourselves.',
        roleLabel: 'Your host',
      },
    },
  },
}
