// content/guia/cities/cdmx.ts
//
// City layer for Mexico City. Reusable across partners. Copy ported verbatim
// from the exported design (prototypes/Guest Stay Experience Design). Do not
// rewrite — this is the approved bilingual copy.

import type { City } from '../types'

const MAPS = (query: string) =>
  `https://www.google.com/maps/search/?api=1&query=${query}`

export const cdmx: City = {
  id: 'cdmx',
  heroImage: '/images/guia/cdmx-banner.jpg',
  neighborhoodOrder: ['Roma Norte', 'Condesa', 'Polanco', 'Centro'],

  neighborhoods: {
    'Roma Norte': {
      name: 'Roma Norte',
      mapUrl: MAPS('Roma+Norte+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'croissant',  name: 'Panadería Gala',                    distance: '4 min caminando',   note: 'Pan y repostería recién horneados, para empezar bien la mañana.' },
          { icon: 'utensilsSm', name: 'Contramar',                         distance: '10 min caminando',  note: 'Las tostadas de atún ya valen el viaje. No se necesita reservación en la comida.' },
          { icon: 'trees',      name: 'Plaza Río de Janeiro',              distance: '3 min caminando',   note: 'Una plaza arbolada con la fuente del David, rodeada de cafés y casonas.' },
          { icon: 'landmark',   name: 'MODO, Museo del Objeto del Objeto', distance: 'Colima 145',        note: 'Diseño y vida cotidiana mexicana en una casona; una hora bien invertida. Cierra lunes.' },
          { icon: 'basket',     name: 'Librería El Péndulo',               distance: 'Álvaro Obregón 86',  note: 'Librería-café de dos pisos; la mesa de autores mexicanos es el souvenir que sí vas a usar.' },
          { icon: 'martini',    name: 'Licorería Limantour',               distance: 'Álvaro Obregón 106', note: 'Top del mundo en coctelería; entre semana antes de las 8 no hay fila.' },
        ],
        en: [
          { icon: 'croissant',  name: 'Panadería Gala',                    distance: '4 min walk',         note: 'Fresh-baked bread and pastries, a good way to start the morning.' },
          { icon: 'utensilsSm', name: 'Contramar',                         distance: '10 min walk',        note: 'The tuna tostadas alone are worth the trip. No reservations needed at lunch.' },
          { icon: 'trees',      name: 'Plaza Río de Janeiro',              distance: '3 min walk',         note: 'A tree-lined square with the David fountain, ringed by cafés and old mansions.' },
          { icon: 'landmark',   name: 'MODO, Museo del Objeto del Objeto', distance: 'Colima 145',         note: 'Mexican design and everyday objects in a townhouse; a well-spent hour. Closed Mondays.' },
          { icon: 'basket',     name: 'Librería El Péndulo',               distance: 'Álvaro Obregón 86',  note: 'Two-story bookstore-café; the Mexican authors table is the souvenir you\'ll actually use.' },
          { icon: 'martini',    name: 'Licorería Limantour',               distance: 'Álvaro Obregón 106', note: 'World\'s-best-list cocktails; weekdays before 8 there\'s no line.' },
        ],
      },
      perfectDay: {
        es: [
          { time: '8:00',  title: 'Café en Avellaneda',                 body: 'Pídelo para llevar; la banca bajo el jacarandá de la esquina es la mejor mesa.' },
          { time: '8:30',  title: 'Una vuelta por Parque México',       body: 'El anfiteatro está vacío antes de las nueve, el mejor momento del día.' },
          { time: '13:00', title: 'Comida en Contramar',                body: 'El atún tostada y el pescado a la talla, en ese orden. Llega antes de la 1:30pm.' },
          { time: '16:00', title: 'Museo Tamayo',                       body: 'Colección compacta, se recorre entera en una hora sin cansarse.' },
          { time: '19:00', title: 'Coctel en Licorería Limantour',      body: 'El Smoking No. 5 es el que piden los que ya conocen la carta.' },
          { time: '21:00', title: 'Cena en Rosetta',                    body: 'Reserva con dos semanas de anticipación; el pan de elote se acaba temprano.' },
        ],
        en: [
          { time: '8:00',  title: 'Coffee at Café Avellaneda',          body: 'Get it to go; the bench under the corner jacaranda is the best table.' },
          { time: '8:30',  title: 'A loop through Parque México',       body: 'The amphitheater sits empty before nine, the best hour the park has.' },
          { time: '13:00', title: 'Lunch at Contramar',                 body: 'Tuna tostada first, pescado a la talla second. Arrive before 1:30pm.' },
          { time: '16:00', title: 'Museo Tamayo',                       body: 'A compact collection, walkable start to finish in an hour without tiring.' },
          { time: '19:00', title: 'Cocktail at Licorería Limantour',    body: 'Order the Smoking No. 5, it\'s what the regulars ask for.' },
          { time: '21:00', title: 'Dinner at Rosetta',                  body: 'Book two weeks out; the corn bread sells out early.' },
        ],
      },
    },

    'Condesa': {
      name: 'Condesa',
      mapUrl: MAPS('Condesa+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'croissant',  name: 'Lardo',                                                     distance: '5 min caminando',                   note: 'Panadería y bistró en una sola parada, perfecto para el desayuno.' },
          { icon: 'utensilsSm', name: 'Ciena',                                                      distance: 'Alfonso Reyes 101, esq. Tacámbaro', note: 'Cocina abierta y terraza que sirve todo el día: desayuno desde las 8, barra por la tarde, cena sin prisa. Llévate la galleta de chocolate con sal.' },
          { icon: 'basket',     name: 'Proyecto Rufina',                                            distance: 'Ámsterdam 133',                     note: 'Ropa y cerámica mexicana en fibras naturales, producción limitada — no venden en línea, solo aquí.' },
          { icon: 'trees',      name: 'Parque México',                                              distance: '6 min caminando',                   note: 'El corazón verde de la colonia, anfiteatro, viveros, y bancas art déco.' },
          { icon: 'iceCream',   name: 'Helados Myka',                                               distance: 'Ámsterdam 264',                     note: 'Helado de yogurt griego batido al momento, con toppings; el postre de la caminata por Ámsterdam.' },
          { icon: 'landmark',   name: 'Centro Cultural Bella Época / Librería Rosario Castellanos', distance: 'Tamaulipas 202',                    note: 'Un cine art déco convertido en la librería techada más grande del país; abre diario hasta las 10 pm.' },
        ],
        en: [
          { icon: 'croissant',  name: 'Lardo',                                                     distance: '5 min walk',                        note: 'Bakery and bistro in one stop, perfect for breakfast.' },
          { icon: 'utensilsSm', name: 'Ciena',                                                      distance: 'Alfonso Reyes 101, esq. Tacámbaro', note: 'Open kitchen and a terrace that serves all day: breakfast from 8, bar menu in the afternoon, unhurried dinner. Take the salted chocolate cookie to go.' },
          { icon: 'basket',     name: 'Proyecto Rufina',                                            distance: 'Ámsterdam 133',                     note: 'Mexican clothing and ceramics in natural fibers, small-batch — no online store, only in person.' },
          { icon: 'trees',      name: 'Parque México',                                              distance: '6 min walk',                        note: 'The green heart of the neighborhood, amphitheater, nursery, art deco benches.' },
          { icon: 'iceCream',   name: 'Helados Myka',                                               distance: 'Ámsterdam 264',                     note: 'Greek frozen yogurt whipped to order, toppings included; the dessert your Ámsterdam walk deserves.' },
          { icon: 'landmark',   name: 'Centro Cultural Bella Época / Librería Rosario Castellanos', distance: 'Tamaulipas 202',                    note: 'An art deco cinema turned the country\'s largest single-room bookstore; open daily until 10 pm.' },
        ],
      },
      perfectDay: {
        es: [
          { time: '8:00',  title: 'Café y pan en Lardo',                     body: 'Llega temprano, las mesas de la terraza se llenan rápido.' },
          { time: '8:30',  title: 'Parque España y Parque México',          body: 'Una caminata tranquila entre los dos parques de la colonia.' },
          { time: '13:00', title: 'Comida en El Parnita',                   body: 'Los tacos de pescado son el platillo por el que vale la pena ir.' },
          { time: '16:00', title: 'Museo Nacional de Antropología',         body: 'A un paseo corto en Chapultepec, la colección más importante del país.' },
          { time: '19:00', title: 'Coctel en Baltra Bar',                   body: 'Mezcal y jazz, en un espacio pequeño e íntimo.' },
          { time: '21:00', title: 'Cena en El Tizoncito',                   body: 'El lugar que se atribuye la invención del taco al pastor.' },
        ],
        en: [
          { time: '8:00',  title: 'Coffee and bread at Lardo',              body: 'Get there early, the terrace tables fill up fast.' },
          { time: '8:30',  title: 'Parque España and Parque México',        body: 'An easy walk between the neighborhood\'s two parks.' },
          { time: '13:00', title: 'Lunch at El Parnita',                    body: 'The fish tacos are the dish worth the trip.' },
          { time: '16:00', title: 'Museo Nacional de Antropología',         body: 'A short ride into Chapultepec, the country\'s most important collection.' },
          { time: '19:00', title: 'Cocktail at Baltra Bar',                 body: 'Mezcal and jazz, in a small, intimate space.' },
          { time: '21:00', title: 'Dinner at El Tizoncito',                 body: 'The spot credited with inventing the taco al pastor.' },
        ],
      },
    },

    'Polanco': {
      name: 'Polanco',
      mapUrl: MAPS('Polanco+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'coffee',    name: 'ENO',                    distance: 'Petrarca 258',     note: 'El café de Enrique Olvera: concha con nata y un espresso antes de los museos.' },
          { icon: 'trees',     name: 'Parque Lincoln',         distance: '4 min caminando',  note: 'Pavorreales, kiosco y las mejores bancas para leer.' },
          { icon: 'landmark',  name: 'Soumaya + Jumex',        distance: 'Plaza Carso',      note: 'Dos museos pared con pared: Soumaya gratis y abierto diario, Jumex de arte contemporáneo — cierra lunes. Un solo viaje, tres horas.' },
          { icon: 'basket',    name: 'Ikal',                   distance: 'Masaryk 340A',     note: 'Concept store de diseño mexicano; el regalo que no parece de aeropuerto.' },
          { icon: 'basket',    name: 'Antara Fashion Hall',    distance: '12 min caminando', note: 'Para una tarde de tiendas o una copa con vista.' },
          { icon: 'martini',   name: 'Ticuchi',                distance: 'Petrarca 254',     note: 'La barra de agaves del equipo de Pujol, a la luz de velas; abre de martes a domingo, desde las 5:30.' },
        ],
        en: [
          { icon: 'coffee',    name: 'ENO',                    distance: 'Petrarca 258', note: 'Enrique Olvera\'s café: concha with cream and an espresso before the museums.' },
          { icon: 'trees',     name: 'Parque Lincoln',         distance: '4 min walk',  note: 'Peacocks, a bandstand, and the best benches for reading.' },
          { icon: 'landmark',  name: 'Soumaya + Jumex',        distance: 'Plaza Carso', note: 'Two museums wall to wall: Soumaya free and open daily, Jumex for contemporary art — closed Mondays. One trip, three hours.' },
          { icon: 'basket',    name: 'Ikal',                   distance: 'Masaryk 340A', note: 'Mexican design concept store; the gift that doesn\'t look duty-free.' },
          { icon: 'basket',    name: 'Antara Fashion Hall',    distance: '12 min walk', note: 'For an afternoon of shopping or a drink with a view.' },
          { icon: 'martini',   name: 'Ticuchi',                distance: 'Petrarca 254', note: 'The Pujol team\'s agave bar, candlelit; Tuesday to Sunday, from 5:30 pm.' },
        ],
      },
      perfectDay: {
        es: [
          { time: '8:00',  title: 'Café en Blend Station',        body: 'Un espacio tranquilo antes de que empiece el ajetreo del día.' },
          { time: '8:30',  title: 'Vuelta por Parque Lincoln',    body: 'El respiro verde de Polanco, con pavorreales incluidos.' },
          { time: '13:00', title: 'Comida en Dulce Patria',       body: 'Cocina mexicana contemporánea de Martha Ortiz, reserva con antelación.' },
          { time: '16:00', title: 'Museo Soumaya',                body: 'Entrada gratuita, una hora fácil, arquitectura que vale la foto.' },
          { time: '19:00', title: 'Copa cerca de Antara',         body: 'Termina la tarde con una copa y algo de shopping ligero.' },
          { time: '21:00', title: 'Cena en Pujol',                body: 'Reserva con semanas de anticipación, vale cada una de ellas.' },
        ],
        en: [
          { time: '8:00',  title: 'Coffee at Blend Station',      body: 'A calm space before the day picks up pace.' },
          { time: '8:30',  title: 'A loop through Parque Lincoln', body: 'Polanco\'s green breather, peacocks included.' },
          { time: '13:00', title: 'Lunch at Dulce Patria',        body: 'Martha Ortiz\'s contemporary Mexican cooking, book ahead.' },
          { time: '16:00', title: 'Museo Soumaya',                body: 'Free entry, an easy hour, architecture worth the photo.' },
          { time: '19:00', title: 'A drink near Antara',          body: 'Close out the afternoon with a drink and some light shopping.' },
          { time: '21:00', title: 'Dinner at Pujol',              body: 'Book weeks ahead, it\'s worth every one of them.' },
        ],
      },
    },

    'Centro': {
      name: 'Centro',
      mapUrl: MAPS('Centro+Historico+Ciudad+de+Mexico'),
      spots: {
        es: [
          { icon: 'coffee',     name: 'Café El Popular',         distance: 'en el Centro', note: 'Abierto casi 24 horas, café de olla y pan dulce.' },
          { icon: 'utensilsSm', name: 'Café de Tacuba',          distance: 'en el Centro', note: 'Desde 1912, cocina mexicana en un salón de azulejos.' },
          { icon: 'basket',     name: 'Mercado de San Juan',     distance: 'en el Centro', note: 'El mercado gourmet de la ciudad, para probar de todo.' },
          { icon: 'landmark',   name: 'Templo Mayor',            distance: 'en el Centro', note: 'Ruinas mexicas a un costado de la Catedral.' },
          { icon: 'landmark',   name: 'Palacio de Bellas Artes', distance: 'en el Centro', note: 'El teatro más bello del país, murales incluidos.' },
          { icon: 'cross',      name: 'El Moro',                 distance: 'en el Centro', note: 'Churros y chocolate desde 1935, abierto toda la noche.' },
        ],
        en: [
          { icon: 'coffee',     name: 'Café El Popular',         distance: 'in the Centro', note: 'Open nearly 24 hours, café de olla and sweet bread.' },
          { icon: 'utensilsSm', name: 'Café de Tacuba',          distance: 'in the Centro', note: 'Since 1912, Mexican cooking in a tiled dining room.' },
          { icon: 'basket',     name: 'Mercado de San Juan',     distance: 'in the Centro', note: 'The city\'s gourmet market, taste a bit of everything.' },
          { icon: 'landmark',   name: 'Templo Mayor',            distance: 'in the Centro', note: 'Aztec ruins right beside the Cathedral.' },
          { icon: 'landmark',   name: 'Palacio de Bellas Artes', distance: 'in the Centro', note: 'The country\'s most beautiful theater, murals included.' },
          { icon: 'cross',      name: 'El Moro',                 distance: 'in the Centro', note: 'Churros and chocolate since 1935, open all night.' },
        ],
      },
      // Source has no perfect-day for Centro; only the home colonia's perfect
      // day is ever rendered, so this stays empty.
      perfectDay: { es: [], en: [] },
    },
  },

  destinations: [
    { name: 'Oaxaca',                 photoUrl: '/images/guides/oaxaca.jpg' },
    { name: 'Tulum',                  photoUrl: '/images/guides/tulum.jpg' },
    { name: 'San Miguel de Allende',  photoUrl: '/images/guides/san-miguel-de-allende.jpg' },
    { name: 'Valle de Bravo',         photoUrl: '/images/guides/valle-de-bravo.jpg' },
    { name: 'Mérida',                 photoUrl: '/images/guides/merida.jpg' },
  ],

  itinerary: {
    es: {
      eyebrow: 'Itinerario',
      title: '48 horas',
      lede: 'Dos días, caminados y comprobados.',
      days: [
        {
          title: 'Día uno, Roma / Condesa',
          items: [
            { time: '08:30', text: 'Café y pan local en Gala Panadería o Rosetta.' },
            { time: '10:00', text: 'Caminata por Río de Janeiro y Parque México.' },
            { time: '13:30', text: 'Comida en Contramar (llega 1:30 o sufre).' },
            { time: '15:00', text: 'Galerías de Roma Norte, entrada libre casi siempre.' },
            { time: '19:30', text: 'Cena ligera o tacos La Once Mil y cocktail en Licorería Limantour.' },
          ],
          note: 'Si quieres ver lo que nunca habías visto, aventúrate a la lucha libre.',
        },
        {
          title: 'Día dos, Centro / Chapultepec',
          items: [
            { time: '09:00', text: 'Zócalo antes de que llegue el calor.' },
            { time: '10:30', text: 'Templo Mayor, Bellas Artes y alrededores a pie.' },
            { time: '13:00', text: 'Churros de El Moro, cerca de Eje Central.' },
            { time: '16:00', text: 'Bosque de Chapultepec y Museo Soumaya.' },
            { time: '20:00', text: 'Cena en Máximo Bistrot o Expendio de Maíz si quieres que te sorprendan.' },
          ],
        },
      ],
    },
    en: {
      eyebrow: 'Itinerary',
      title: '48 hours',
      lede: 'Two days, walked and checked.',
      days: [
        {
          title: 'Day one, Roma / Condesa',
          items: [
            { time: '08:30', text: 'Coffee and local bread at Gala Panadería or Rosetta.' },
            { time: '10:00', text: 'A walk through Río de Janeiro and Parque México.' },
            { time: '13:30', text: 'Lunch at Contramar (arrive by 1:30 or suffer).' },
            { time: '15:00', text: 'Roma Norte galleries, free entry most of the time.' },
            { time: '19:30', text: 'A light dinner or tacos at La Once Mil, and a cocktail at Licorería Limantour.' },
          ],
          note: 'If you want to see something you never have, take a chance on lucha libre.',
        },
        {
          title: 'Day two, Centro / Chapultepec',
          items: [
            { time: '09:00', text: 'The Zócalo before the heat arrives.' },
            { time: '10:30', text: 'Templo Mayor, Bellas Artes, and the surroundings on foot.' },
            { time: '13:00', text: 'Churros at El Moro, near Eje Central.' },
            { time: '16:00', text: 'Bosque de Chapultepec and Museo Soumaya.' },
            { time: '20:00', text: 'Dinner at Máximo Bistrot or Expendio de Maíz if you want to be surprised.' },
          ],
        },
      ],
    },
  },

  copy: {
    es: {
      navLabel: 'Tu estancia',
      heroEyebrow: 'Curado por {host} · Potenciado por Lagomplan',
      heroTitle: 'Bienvenido a la Ciudad de México.',
      heroSub: 'Todo lo que necesitas para tu estancia en {neighborhood}, preparado como lo haría un amigo, no un buscador.',
      beginExploring: 'Empezar a explorar',
      beforeEyebrow: 'Antes de llegar',
      beforeH2: 'Un inicio tranquilo para tu viaje',
      beforeLede: 'Lo básico y práctico, para que dejes de pensar en logística en cuanto aterrices.',
      arrivalItems: [
        { icon: 'plane',     title: 'Aeropuerto',      body: 'La mayoría de los vuelos llegan al AICM (Terminal 1 o 2). De ahí, un taxi autorizado o Uber tarda 30–45 min a {neighborhood}. Podemos ofrecerte también transporte privado.' },
        { icon: 'car',       title: 'Transporte',      body: 'Usa Uber o Didi, más barato y seguro que parar un taxi en la calle. El Metro es excelente si te sientes cómodo entre multitudes. Podemos ofrecerte también transporte privado.' },
        { icon: 'cloudSun',  title: 'Clima',           body: 'Julio es temporada de lluvias, mañanas soleadas, lluvias breves por la tarde. Lleva capas y una chamarra ligera para la lluvia.' },
        { icon: 'banknote',  title: 'Dinero',          body: 'Las tarjetas se aceptan ampliamente. Lleva algo de efectivo en pesos para mercados, propinas y comida callejera. En restaurantes, la propina recomendada es 10–15%; redondea en taxis y puestos casuales.' },
        { icon: 'wifi',      title: 'Conectividad',    body: 'Un eSIM se activa en minutos. ', link: { text: 'Consigue el tuyo con Airalo aquí', href: 'https://airalo.tpm.li/xkRXTIKe', after: '. El wifi es confiable en la propiedad y en la mayoría de los cafés.' } },
        { icon: 'shield',    title: 'Seguridad',       body: 'Aplica el sentido común habitual en ciudad, usa apps de transporte por la noche y mantén tus objetos de valor fuera de vista.' },
        { icon: 'briefcase', title: 'Equipaje',        body: 'Zapatos cómodos para caminar, un outfit elegante para la cena, y una capa ligera para las noches frescas.' },
        { icon: 'droplet',   title: 'Agua de la llave', body: 'Te recomendamos agua embotellada o filtrada para tomar. Es segura para bañarte y lavarte los dientes.' },
        { icon: 'moon',      title: 'Llegar tarde',    body: 'Llega a la hora que sea, no hay problema. Solo te pedimos entrar con calma, es un edificio con vecinos.' },
        { icon: 'parking',   title: 'Estacionamiento', body: 'El estacionamiento en la calle es limitado en la zona. Te recomendamos llegar en Uber o Didi en vez de traer coche.' },
      ],
      neighborhoodEyebrow: 'Tu colonia',
      neighborhoodH2Prefix: 'La vida alrededor de ',
      neighborhoodLede: 'Todo está a pocos pasos. Esto es lo que te recomendaría si me preguntaras en el desayuno.',
      openInMapsLabel: 'Ver lista en Maps',
      perfectDayEyebrow: 'Un día perfecto',
      perfectDayH2: 'Si tuviera un solo día aquí',
      perfectDayLede: 'Esto es exactamente lo que haría, de principio a fin.',
      moodEyebrow: 'Explora según tu ánimo',
      moodH2: '¿Qué se te antoja hoy?',
      moodLede: 'Elige un ánimo, no una categoría.',
      moods: [
        { id: 'hungry',    icon: 'utensils', label: 'Tengo hambre',          title: 'Para cuando tienes hambre', items: [
          { name: 'Contramar',           note: 'Mariscos, sin reservación para la comida.' },
          { name: 'Panadería Rosetta',   note: 'Panes que valen madrugar.' },
          { name: 'Lalo!',               note: 'Desayuno y comida casuales, con producto de mercado.' },
        ]},
        { id: 'culture',   icon: 'landmark', label: 'Quiero cultura',         title: 'Para la cultura', items: [
          { name: 'Museo Tamayo',        note: 'Arte contemporáneo, una hora fácil.' },
          { name: 'Casa Luis Barragán',  note: 'Reserva con semanas de anticipación, grupos pequeños con horario.' },
          { name: 'Kurimanzutto',        note: 'Una galería líder de arte contemporáneo, entrada gratuita.' },
        ]},
        { id: 'kids',      icon: 'baby',     label: 'Viajo con niños',        title: 'Con niños', items: [
          { name: 'Parque México',              note: 'Juegos infantiles y senderos amplios para piernitas pequeñas.' },
          { name: 'Papalote Museo del Niño',    note: 'Exhibiciones interactivas, llena fácilmente medio día.' },
          { name: 'Zoológico de Chapultepec',   note: 'Entrada gratuita, senderos con sombra, a un taxi corto.' },
        ]},
        { id: 'nightlife', icon: 'martini',  label: 'Quiero vida nocturna',   title: 'Para la noche', items: [
          { name: 'Licorería Limantour',  note: 'Coctelería de clase mundial, llega antes de las 9pm.' },
          { name: 'Departamento',         note: 'Rooftop, DJ en vivo, ambiente más animado.' },
          { name: 'Bar Federalista',      note: 'Enfocado en mezcal, relajado y sin pretensiones.' },
        ]},
        { id: 'hidden',    icon: 'compass',  label: 'Lugares escondidos',     title: 'Lugares escondidos', items: [
          { name: 'Mercado de Medellín',  note: 'Un mercado que pocos turistas encuentran, prueba los puestos caribeños.' },
          { name: 'Jardín Pushkin',       note: 'Un parque diminuto y tranquilo que la mayoría de las guías se saltan.' },
          { name: 'Café Nin',             note: 'Escondido, fácil de pasar de largo, vale la pena encontrarlo.' },
        ]},
        { id: 'short',     icon: 'clock',    label: 'Solo tengo unas horas',  title: 'Solo unas horas', items: [
          { name: 'Vuelta por Parque España',        note: '20 minutos, de principio a fin.' },
          { name: 'Cafebrería El Péndulo',           note: 'Café y libros, todo en un solo lugar.' },
          { name: 'Mirador Torre Latinoamericana',   note: 'Elevador rápido, vista inigualable.' },
        ]},
      ],
      closeLabel: 'Cerrar',
      todayDateLabel: 'Esta semana en la Ciudad de México',
      todayH2: 'Ahora mismo en la ciudad',
      weatherTemp: '24° / 14°',
      weatherBody: 'Parcialmente nublado, con probable lluvia por la tarde, lleva una capa ligera para la lluvia.',
      todayItems: [
        { tag: 'Esta semana',   title: 'Feria de las Culturas Amigas',                  body: 'Un festival cultural de verano en el Zócalo, durante todo el mes.' },
        { tag: 'Mercado',       title: 'Tianguis dominical, Mercado de Medellín',       body: 'El mercado semanal se extiende a la calle, ve con hambre.' },
        { tag: 'Música en vivo', title: 'Jazzatlán en la Fonoteca Nacional',            body: 'Sesiones de jazz en vivo gratuitas, a un taxi corto de {neighborhood}.' },
        { tag: 'Atardecer',     title: 'Mirador Torre Latinoamericana',                 body: 'Los cielos suelen despejarse después de la lluvia de la tarde, vale la pena el timing.' },
      ],
      expEyebrow: 'Experiencias',
      expH2: 'Vale la pena el tiempo',
      expLede: 'Una lista corta, a propósito.',
      experiences: [
        { id: 'exp-lucha',      title: 'Lucha libre en la Arena México',                    body: 'Ruidoso, inolvidable, e inconfundiblemente de la Ciudad de México.' },
        { id: 'exp-xochimilco', title: 'Tarde en trajinera, Xochimilco',                    body: 'Un paseo lento por los canales, ve entre semana para evitar las multitudes.' },
        { id: 'exp-frida',      title: 'Museo Frida Kahlo, entrada con horario',            body: 'Reserva con al menos dos semanas de anticipación, los boletos se agotan rápido.' },
        { id: 'exp-ballet',     title: 'Ballet Folklórico, Palacio de Bellas Artes',        body: 'Hora y media, dentro de uno de los edificios más hermosos de la ciudad.' },
      ],
      foodEyebrow: 'Comida',
      foodH2: 'Editorial, no interminable',
      foodLede: 'Una recomendación por antojo.',
      foodCollections: [
        { tag: 'Desayuno',      name: 'Panadería Rosetta',    note: 'Llega antes de que se acaben los panes de guayaba.' },
        { tag: 'Tacos',         name: 'El Vilsito',           note: 'Vulcanizadora de día, taquería de noche.' },
        { tag: 'Café',          name: 'Café Avellaneda',      note: 'De lote pequeño, sin prisa.' },
        { tag: 'Cocteles',      name: 'Licorería Limantour',  note: 'Consistentemente uno de los mejores bares del mundo.' },
        { tag: 'Alta cocina',   name: 'Quintonil',            note: 'Reserva con un mes de anticipación, vale la espera.' },
        { tag: 'Joya escondida', name: 'Café Nin',            note: 'Fácil de pasar de largo, difícil de olvidar.' },
      ],
      continueEyebrow: 'Más allá de esta estancia',
      continueH2: '¿Listo para explorar más allá de tu estancia?',
      continueLede: 'Arma un itinerario personalizado, hoteles, días y presupuesto, en menos de un minuto.',
      continueCta: 'Planifica mi próximo viaje →',
      stickyCta: 'Personalizar mi viaje en 60 segundos',
      discoverEyebrow: 'Descubre más',
      discoverH2: 'Lagomplan va más allá de esta ciudad',
      footer: 'lagomplan · experiencia de huésped',
      hostLetter: {
        eyebrow: 'Una carta de tu anfitrión',
        quote: 'La Ciudad de México no se visita, se recorre dos veces, y aún faltan calles.',
        body: 'Esta guía nació de una pregunta que nos hacen nuestros huéspedes cada semana: ¿a dónde voy hoy? No es una lista exhaustiva, es un recorte curado de lo que de verdad vale la pena. Cada recomendación la caminamos, la comimos y la comprobamos nosotros mismos.',
        roleLabel: 'Tu anfitrión',
      },
    },

    en: {
      navLabel: 'Guest Stay',
      heroEyebrow: 'Curated by {host} · Enhanced by Lagomplan',
      heroTitle: 'Welcome to Mexico City.',
      heroSub: 'Everything you need for your stay in {neighborhood}, prepared like a friend would prepare it, not a search engine.',
      beginExploring: 'Begin exploring',
      beforeEyebrow: 'Before you arrive',
      beforeH2: 'A calm start to your trip',
      beforeLede: 'The practical basics, so you can stop thinking about logistics the moment you land.',
      arrivalItems: [
        { icon: 'plane',     title: 'Airport',        body: 'Most flights land at AICM (Terminal 1 or 2). From there, an authorized airport taxi or Uber takes 30–45 min to {neighborhood}. We can also offer you private transportation.' },
        { icon: 'car',       title: 'Transportation', body: 'Use Uber or Didi, cheaper and safer than hailing on the street. The Metro is excellent if you\'re comfortable with crowds. We can also offer you private transportation.' },
        { icon: 'cloudSun',  title: 'Weather',        body: 'July is rainy season, sunny mornings, brief afternoon showers. Pack layers and a light rain jacket.' },
        { icon: 'banknote',  title: 'Money',          body: 'Cards are widely accepted. Keep some pesos in cash for markets, tips, and street food. In restaurants, 10–15% is the recommended tip; round up for taxis and casual spots.' },
        { icon: 'wifi',      title: 'Connectivity',   body: 'An eSIM activates in minutes. ', link: { text: 'Get yours through Airalo here', href: 'https://airalo.tpm.li/xkRXTIKe', after: '. Wi-Fi is reliable at the property and most cafés.' } },
        { icon: 'shield',    title: 'Safety',         body: 'Standard city awareness applies, stick to rideshare apps at night and keep valuables out of sight.' },
        { icon: 'briefcase', title: 'Packing',        body: 'Comfortable walking shoes, one nice outfit for dinner, and a light layer for cooler evenings.' },
        { icon: 'droplet',   title: 'Tap water',      body: 'We recommend bottled or filtered water for drinking. It\'s safe for showering and brushing your teeth.' },
        { icon: 'moon',      title: 'Coming back late', body: 'Arrive whenever you like, no need to worry. Just come in quietly, it\'s a building with neighbors.' },
        { icon: 'parking',   title: 'Parking',        body: 'Street parking is limited in the area. We recommend arriving by Uber or Didi instead of bringing a car.' },
      ],
      neighborhoodEyebrow: 'Your neighborhood',
      neighborhoodH2Prefix: 'Life around ',
      neighborhoodLede: 'Everything\'s within a short walk. Here\'s what I\'d point you to if you asked me at breakfast.',
      openInMapsLabel: 'Open list in Maps',
      perfectDayEyebrow: 'A perfect day',
      perfectDayH2: 'If I had one day here',
      perfectDayLede: 'This is exactly what I\'d do, start to finish.',
      moodEyebrow: 'Explore by mood',
      moodH2: 'What are you in the mood for?',
      moodLede: 'Pick a feeling, not a category.',
      moods: [
        { id: 'hungry',    icon: 'utensils', label: "I'm hungry",          title: 'For when you\'re hungry', items: [
          { name: 'Contramar',           note: 'Seafood, no reservation needed for lunch.' },
          { name: 'Panadería Rosetta',   note: 'Pastries worth setting an alarm for.' },
          { name: 'Lalo!',               note: 'Casual, market-driven breakfast and lunch.' },
        ]},
        { id: 'culture',   icon: 'landmark', label: 'I want culture',      title: 'For culture', items: [
          { name: 'Museo Tamayo',        note: 'Contemporary art, an easy hour.' },
          { name: 'Casa Luis Barragán',  note: 'Book weeks ahead, small timed groups.' },
          { name: 'Kurimanzutto',        note: 'A leading contemporary gallery, free entry.' },
        ]},
        { id: 'kids',      icon: 'baby',     label: 'Traveling with kids', title: 'With kids', items: [
          { name: 'Parque México',              note: 'Playgrounds and wide open paths for little legs.' },
          { name: 'Papalote Museo del Niño',    note: 'Hands-on exhibits, easily fills half a day.' },
          { name: 'Chapultepec Zoo',            note: 'Free entry, shaded paths, a short taxi away.' },
        ]},
        { id: 'nightlife', icon: 'martini',  label: 'I want nightlife',    title: 'For the night', items: [
          { name: 'Licorería Limantour',  note: 'World-class cocktails, arrive before 9pm.' },
          { name: 'Departamento',         note: 'Rooftop, DJ sets, a livelier crowd.' },
          { name: 'Bar Federalista',      note: 'Mezcal-forward, low-key and unpretentious.' },
        ]},
        { id: 'hidden',    icon: 'compass',  label: 'Hidden places',       title: 'Hidden places', items: [
          { name: 'Mercado de Medellín',  note: 'A market few tourists find, try the Caribbean stalls.' },
          { name: 'Jardín Pushkin',       note: 'A tiny, quiet park most guidebooks skip.' },
          { name: 'Café Nin',             note: 'Tucked away, easy to miss, worth finding.' },
        ]},
        { id: 'short',     icon: 'clock',    label: 'Only a few hours',    title: 'A few hours only', items: [
          { name: 'Parque España loop',              note: '20 minutes, start to finish.' },
          { name: 'Cafebrería El Péndulo',           note: 'Coffee and browsing, all in one stop.' },
          { name: 'Mirador Torre Latinoamericana',   note: 'Quick elevator up, unbeatable view.' },
        ]},
      ],
      closeLabel: 'Close',
      todayDateLabel: 'This week in Mexico City',
      todayH2: 'Right now in the city',
      weatherTemp: '24° / 14°',
      weatherBody: 'Partly cloudy, afternoon showers likely, bring a light rain layer.',
      todayItems: [
        { tag: 'This week',   title: 'Feria de las Culturas Amigas',                 body: 'A summer cultural festival in the Zócalo, running through the month.' },
        { tag: 'Market',      title: 'Mercado de Medellín, Sunday tianguis',         body: 'The weekly outdoor market spills onto the street, go hungry.' },
        { tag: 'Live music',  title: 'Jazzatlán at Fonoteca Nacional',               body: 'Free live jazz sets, a short taxi from {neighborhood}.' },
        { tag: 'Sunset',      title: 'Mirador Torre Latinoamericana',                body: 'Clearest skies tend to follow the afternoon rain, worth timing for.' },
      ],
      expEyebrow: 'Experiences',
      expH2: 'Worth the time',
      expLede: 'A short list, on purpose.',
      experiences: [
        { id: 'exp-lucha',      title: 'Lucha libre at Arena México',                     body: 'Loud, unforgettable, and unmistakably Mexico City.' },
        { id: 'exp-xochimilco', title: 'Afternoon on a trajinera, Xochimilco',            body: 'A slow boat ride through the canals, go on a weekday to skip the crowds.' },
        { id: 'exp-frida',      title: 'Museo Frida Kahlo, timed entry',                  body: 'Book at least two weeks ahead, tickets sell out fast.' },
        { id: 'exp-ballet',     title: 'Ballet Folklórico, Palacio de Bellas Artes',      body: 'An hour and a half, inside one of the city\'s most beautiful buildings.' },
      ],
      foodEyebrow: 'Food',
      foodH2: 'Editorial, not endless',
      foodLede: 'One pick per craving.',
      foodCollections: [
        { tag: 'Breakfast',   name: 'Panadería Rosetta',    note: 'Get there before the guava rolls sell out.' },
        { tag: 'Tacos',       name: 'El Vilsito',           note: 'A tire shop by day, taquería by night.' },
        { tag: 'Coffee',      name: 'Café Avellaneda',      note: 'Small-batch, unhurried.' },
        { tag: 'Cocktails',   name: 'Licorería Limantour',  note: 'Consistently one of the world\'s best bars.' },
        { tag: 'Fine dining', name: 'Quintonil',            note: 'Book a month out, it\'s worth the wait.' },
        { tag: 'Hidden gem',  name: 'Café Nin',             note: 'Easy to walk past, hard to forget.' },
      ],
      continueEyebrow: 'Beyond this stay',
      continueH2: 'Ready to explore beyond your stay?',
      continueLede: 'Build a personalized itinerary, hotels, days, and a budget, in less than a minute.',
      continueCta: 'Plan my next trip →',
      stickyCta: 'Plan my trip in 60 seconds',
      discoverEyebrow: 'Discover more',
      discoverH2: 'Lagomplan goes further than this city',
      footer: 'lagomplan · guest stay experience',
      hostLetter: {
        eyebrow: 'A letter from your host',
        quote: 'Mexico City isn\'t visited, it\'s walked twice, and there are still streets left.',
        body: 'This guide came from a question our guests ask us every week: where do I go today? It isn\'t exhaustive, it\'s a curated cut of what\'s truly worth it. We walked, ate, and checked every recommendation ourselves.',
        roleLabel: 'Your host',
      },
    },
  },
}
