/**
 * app/[locale]/examples/page.tsx — /ejemplos (ES) · /examples (EN)
 *
 * Showcases real, previously-generated trips as public read-only examples.
 * Server Component: fetches every trips.is_public_example = true row from
 * Supabase (single source of truth — flip the DB flag and a trip
 * appears/disappears here without a deploy). Card links intentionally always
 * point at /es/planificador regardless of page locale — the trips
 * themselves are Spanish-language content (see PASO 0/2 task notes).
 *
 * Curated bilingual marketing copy (the "Fíjate en..." teaser text) lives in
 * EXAMPLE_COPY below, keyed by trip id, rather than a new trips column —
 * consistent with how this codebase already keeps editorial bilingual copy
 * in code (content/guia/) rather than the database, and avoids a schema
 * change (or a JSONB column) just to hold 2 short strings per trip. Any
 * trip flagged is_public_example without a matching entry here still
 * renders — falls back to its own title/destination — so flipping the flag
 * alone is never silently a no-op, it just ships without curated copy until
 * someone adds one.
 */

import type { Metadata } from 'next'
import { buildAlternates, buildOpenGraph } from '../../../lib/seo'
import { getSupabaseAdmin } from '../../../lib/supabase/server'
import type { Locale } from '../../../i18n'
import ExampleCard from '../../../components/examples/ExampleCard'

const EXAMPLE_COPY: Record<string, {
  title_es: string; title_en: string
  body_es: string; body_en: string
}> = {
  'f27f61eb-9f6f-4eb1-b874-11e0b04d33e7': {
    title_es: 'Copenhague · 5 días · grupo de amigos',
    title_en: 'Copenhagen · 5 days · group of friends',
    body_es: 'Fíjate en el presupuesto desglosado por categoría, y en que cada actividad ya trae su horario y su porqué.',
    body_en: 'Notice the budget broken down by category, and how every activity already comes with its time and its reasoning.',
  },
  'b0fef49b-5049-46ed-9b4f-40dc9c56a613': {
    title_es: 'Cartagena · en familia',
    title_en: 'Cartagena · with family',
    body_es: 'Este trae el itinerario adaptado al ritmo de una familia y la checklist completa de qué reservar antes de llegar.',
    body_en: 'This one adapts the itinerary to a family\'s pace, plus the full checklist of what to book before arriving.',
  },
  'aa134594-e4c9-42e3-a10b-bfb395c37674': {
    title_es: 'Ensenada · en pareja',
    title_en: 'Ensenada · as a couple',
    body_es: 'Un fin de semana corto y bien resuelto. Nota cómo el plan organiza tiempos cortos sin sentirse apretado.',
    body_en: 'A short, well-organized weekend. Notice how the plan handles tight timing without feeling rushed.',
  },
}

// Curated entries render first, in this declared order (matches the
// approved card ordering); any additional is_public_example trip without
// curated copy is appended after, oldest-first.
const CURATED_ORDER = Object.keys(EXAMPLE_COPY)

type ExampleTripRow = {
  id: string
  title: string | null
  destination: string | null
  travelers: string | null
}

async function loadExampleTrips(): Promise<ExampleTripRow[]> {
  const admin = getSupabaseAdmin()
  const { data, error } = await admin
    .from('trips')
    .select('id, title, destination, travelers')
    .eq('is_public_example', true)
    .order('created_at', { ascending: true })
  if (error || !data) return []
  return (data as unknown as ExampleTripRow[]).slice().sort((a, b) => {
    const ai = CURATED_ORDER.indexOf(a.id)
    const bi = CURATED_ORDER.indexOf(b.id)
    if (ai === -1 && bi === -1) return 0
    if (ai === -1) return 1
    if (bi === -1) return -1
    return ai - bi
  })
}

function fallbackCopy(trip: ExampleTripRow, isES: boolean) {
  const title = trip.title?.trim() || trip.destination || (isES ? 'Viaje de ejemplo' : 'Example trip')
  return {
    title,
    body: isES
      ? 'Un plan real generado por nuestra IA. Explora el itinerario completo.'
      : 'A real plan generated by our AI. Explore the full itinerary.',
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: Locale }>
}): Promise<Metadata> {
  const { locale } = await params
  return {
    title:      locale === 'es' ? 'Esto es lo que recibes' : 'This is what you get',
    alternates: buildAlternates('examples'),
    openGraph:  buildOpenGraph(locale),
  }
}

export default async function ExamplesPage({
  params,
}: {
  params: Promise<{ locale: Locale }>
}) {
  const { locale } = await params
  const isES = locale === 'es'
  const trips = await loadExampleTrips()

  return (
    <main className="pt-[100px] min-h-screen" style={{ background: '#FFF9F3' }}>
      <div className="page-inner py-24 max-[768px]:py-16">
        <span className="sec-label">
          {isES ? 'Ejemplos' : 'Examples'}
        </span>
        <h1 className="font-sans text-[40px] max-[768px]:text-[30px] font-bold text-[#0F3A33] leading-[1.1] mb-5 [text-wrap:balance]">
          {isES ? 'Esto es lo que recibes.' : 'This is what you get.'}
        </h1>
        <p className="font-sans text-[15px] text-[#3E5F58] leading-[1.7] max-w-[640px] mb-14 [text-wrap:pretty]">
          {isES
            ? <>No es una lista de ideas. Es tu viaje completo: itinerario día por día con horarios, hotel{' '}recomendado y por qué, presupuesto desglosado, y todo lo que falta reservar, en orden. Estos son planes reales que ya generamos. Míralos, y si quieres el tuyo, es gratis para los primeros 3 viajes.</>
            : <>It's not a list of ideas. It's your complete trip: a day-by-day itinerary with times, a recommended{' '}hotel and why, a broken-down budget, and everything left to book, in order. These are real plans we already generated. Take a look, and if you want your own, it's free for your first 3 trips.</>}
        </p>

        {trips.length === 0 ? (
          <p className="font-sans text-[14px] text-[#8A8A8A]">
            {isES ? 'No hay ejemplos disponibles por ahora.' : 'No examples available right now.'}
          </p>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 md:gap-6">
            {trips.map((trip, i) => {
              const curated = EXAMPLE_COPY[trip.id]
              const { title, body } = curated
                ? { title: isES ? curated.title_es : curated.title_en, body: isES ? curated.body_es : curated.body_en }
                : fallbackCopy(trip, isES)
              const mapVariants = ['a', 'b', 'c'] as const
              return (
                <ExampleCard
                  key={trip.id}
                  ctaId={`examples_view_plan_${trip.id}`}
                  title={title}
                  body={body}
                  ctaLabel={isES ? 'Ver el plan completo →' : 'See the full plan →'}
                  href={`/es/planificador?trip_id=${trip.id}`}
                  mapVariant={mapVariants[i % mapVariants.length]}
                />
              )
            })}
          </div>
        )}
      </div>
    </main>
  )
}
